informatici/openhospital-core

pom.xml

This PR adds the [Maven Assembly Plugin](http://maven.apache.org/plugins/maven-assembly-plugin/index.html) to package source and project files as zip.  
It uses the *project* and *src* descriptor files packaged with the plugin (see [here](http://maven.apache.org/plugins/maven-assembly-plugin/descriptor-refs.html)).  
These are the generated artefacts upon issuing `mvn install` or `mvn assembly:single`:
```
OH-core-1.9-project.tar.bz2
OH-core-1.9-project.tar.gz
OH-core-1.9-project.zip
OH-core-1.9-src.tar.bz2
OH-core-1.9-src.tar.gz
OH-core-1.9-src.zip
```
The "project" artifact contain all project files needed to build the project, while the "src" files only contain the source files. If needed, this can be further customized by using a custom assembly descriptor (see …

Add maven plugin to create project and source zip files

---

rsc/applicationContext.xml

To support different spring data jpa minor versions, it's been reference the unversioned xsd schema from the namespace declaration.
In this way the xsd, which **is** present in the jars, is not fetched via http and the application starts even without internet connection.
More detail in Jira issue: https://openhospital.atlassian.net/browse/OP-141

remove data jpa schema version

---

pom.xml

The Boundless repository appears to be offline and is causing CI builds failures - see for instance https://travis-ci.org/github/informatici/openhospital-core/jobs/676842582#L1085
This repository builds fine without it anyway.

Remove reference to Boundless maven repository

---

.github/workflows/maven.yml

Since tests are now performed against an in-memory db (#132 ), we can get rid of the docker-compose step in the CI.

Remove docker step from github CI

---

src/main/java/org/isf/dicom/manager/DicomManagerInterface.java
src/main/java/org/isf/medicalstock/service/LotIoOperationRepository.java
src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperationRepository.java
src/main/java/org/isf/visits/service/VisitsIoOperationRepository.java

This replaces this [PR](https://github.com/informatici/openhospital-core/pull/135).
Removed redundant public modifier for interface methods. Note some of the file already had some methods without the public so this makes things consistent.
Even though it looks like a lot of changes it really isn't as the files each were a mixture of spaces and tabs and I reformatted them all to tabs before applying the change.

Remove redundant public for interface methods

---

pom.xml

Temporarily reverts informatici/openhospital-core#123, as we need to solve some incompatibility issues with Jasper before bumping its version (https://openhospital.atlassian.net/browse/OP-104) or migrate to the rebranded library (https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports ).

Revert "Bump jasperreports from 3.0.0 to 3.5.3"

---

src/org/isf/stat/manager/JasperReportsManager.java

I have modified the methods that adds date parameters to the parameter Hashmap that is passed to the Jasper engine when creating reports.
The public signature has not changed so that no other changes are needed in the calling code. The dates (as string) are parsed to java.util.Date internally.
This pull request is dependent on an equal pull request in the openhospital-gui project where I have modified the individual reports to handle date parameters as java.util.Date objects.

OP-105-string_to_date_in_jasper_reports

---

README.md

Remove note about `mvn` version 3.2.5 begin required now that JDK 8 is used.
See Maven [release history](https://maven.apache.org/docs/history.html) to see that the most recent version can be used and is only dependent on JDK 7.

Remove note about mvn 3.2.5 now that JDK 8 is used

---

src/main/java/org/isf/dicom/manager/FileSystemDicomManager.java
src/main/java/org/isf/generaldata/ExaminationParameters.java
src/main/java/org/isf/generaldata/GeneralData.java
src/main/java/org/isf/generaldata/MessageBundle.java
src/main/java/org/isf/generaldata/PropertyReader.java
src/main/java/org/isf/generaldata/SmsParameters.java
src/main/java/org/isf/generaldata/TxtPrinter.java
src/main/java/org/isf/generaldata/Version.java
src/main/java/org/isf/serviceprinting/manager/PrintReceipt.java
src/main/java/org/isf/sms/providers/GSMParameters.java
src/main/java/org/isf/sms/providers/SkebbyGateway.java
src/main/java/org/isf/sms/providers/SkebbyParameters.java
src/main/java/org/isf/sms/service/SmsSender.java
src/main/java/org/isf/sms/service/SmsSenderGSM.java
src/main/java/org/isf/stat/manager/JasperReportsManager.java
src/main/java/org/isf/utils/db/DbJpaUtil.java
src/main/java/org/isf/utils/db/DbQueryLogger.java
src/main/java/org/isf/utils/db/DbSingleConn.java
src/main/java/org/isf/utils/db/DbSingleJpaConn.java
src/main/java/org/isf/utils/exception/OHException.java
src/main/java/org/isf/xmpp/manager/Interaction.java
src/main/java/org/isf/xmpp/service/Server.java
src/test/java/org/isf/lab/test/Tests.java

Non-constant concatenations in logging messages are evaluated at runtime even when the logging message is not logged; this can negatively impact performance. Thus these changes use a parameterized log message instead which will not be evaluated when logging is disabled.
Because of the large number of files, reformatting of the files was not done in this PR.

Replace concatenation with parameterized log message

---

src/main/java/org/isf/utils/db/CSV2SQL.java
src/main/java/org/isf/utils/excel/ExcelExporter.java

Now that Java 8 is the base version, replace `try-finally` with `try` with `resources`.  
Note that most of the changes are the result of reformatting the file to project standards are just white space changes.
If you want to hide the white space changes:

Replaces try-finally with try with resources

---

pom.xml

This replaces this [PR](https://github.com/informatici/openhospital-core/pull/140) which updates to 5.x branch which currently is not compatible.

Update Spring from 4.3.18 to latest 4.x branch version 4.3.28

---

pom.xml

This replaces these two PRs:
- [spring-boot-test](https://github.com/informatici/openhospital-core/pull/162) 
- [spring-boot-starter-test](https://github.com/informatici/openhospital-core/pull/161)
by upgrading to compatible version.

Update SpringBootTest and SpringBootStarterTest from 1.4.0 to compatible version 1.5.22

---

src/main/java/org/isf/accounting/manager/BillBrowserManager.java
src/main/java/org/isf/accounting/service/AccountingIoOperations.java
src/test/java/org/isf/accounting/test/Tests.java

Per [OP-247](https://openhospital.atlassian.net/jira/software/c/projects/OP/issues/OP-247) add new method that doesn't require the casting of null to `BillItems` to get all items.   The new method is `getAllBills(dateFrom, dateTo)`.   
Also added junit tests for both methods.

OP-247 Method ambiguity

---

src/test/java/org/isf/accounting/test/Tests.java

Add missing comparison test (**isTrue()**) otherwise the result of the **equals()** test is ignored.

Add missing comparison test to assertThat()

---

pom.xml

I had to exclude transient dep to com.lowagie it was in version which was not found in maven central repo

[OP-282] excluded transient dependency to itext in jesperreports

---

src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java

Fix a case where code prevents a class from being subclassed (because of the `private` modifier) by some frameworks (e.g. Spring and Hibernate) at runtime.

Chore: Private method cannot be overridden at runtime

---

src/main/java/org/isf/hospital/model/Hospital.java

Found using SpotBugs
The code compares java.lang.String objects for reference equality using the == operator. Unless both strings are either constants in a source file, or have been interned using the String.intern() method, the same string value may be represented by two different String objects and thus fail.  
Replaced with `equalsIgnoreCase()` to match the other tests.

Chore Fix comparison of String objects

---

src/main/java/org/isf/disease/model/Disease.java
src/main/java/org/isf/dlvrrestype/model/DeliveryResultType.java
src/main/java/org/isf/dlvrtype/model/DeliveryType.java
src/main/java/org/isf/exa/model/Exam.java
src/main/java/org/isf/exa/model/ExamRow.java
src/main/java/org/isf/exatype/model/ExamType.java
src/main/java/org/isf/hospital/model/Hospital.java
src/main/java/org/isf/medtype/model/MedicalType.java
src/main/java/org/isf/menu/model/GroupMenu.java
src/main/java/org/isf/menu/model/User.java
src/main/java/org/isf/menu/model/UserGroup.java
src/main/java/org/isf/menu/model/UserMenuItem.java
src/main/java/org/isf/pregtreattype/model/PregnantTreatmentType.java
src/main/java/org/isf/vaccine/model/Vaccine.java
src/main/java/org/isf/vactype/model/VaccineType.java
src/main/java/org/isf/ward/model/Ward.java

Found with SonarLint
TItle: Null checks should not be used with "instanceof"
Description: There's no need to null test in conjunction with an `instanceof` test. null is not an `instanceof` anything, so a null check is redundant.
So I removed the `null` checks.

Chore No need for null check with instanceof

---

pom.xml
src/main/java/org/isf/admtype/manager/AdmissionTypeBrowserManager.java
src/test/java/org/isf/admtype/test/Tests.java
src/test/java/org/isf/agetype/test/Tests.java

Updated `assertj` to something newer to use newer features
Also removed from `AgeTypeBrowserManager` two methods that are not needed given autowiring.  I also grepped across all the repos and found no uses:
`````
public AdmissionTypeIoOperation getIoOperations() {
return ioOperations;
}
public void setIoOperations(AdmissionTypeIoOperation ioOperations) {
this.ioOperations = ioOperations;
}

OP-374 increase coverage for admtype and agetype packages

---

src/main/java/org/isf/admtype/manager/AdmissionTypeBrowserManager.java
src/main/java/org/isf/agetype/manager/AgeTypeBrowserManager.java
src/test/java/org/isf/admtype/test/Tests.java
src/test/java/org/isf/agetype/test/Tests.java

Given the decision to keep the "test" prefix on test methods for the time being; added them and did simple reformatting of the `Manager` classes.
This is for the admtype and agetype packages.

OP-374 Add test prefix; format Manager class

---

src/main/java/org/isf/patient/manager/PatientBrowserManager.java
src/main/java/org/isf/patient/model/Patient.java
src/main/java/org/isf/patient/service/PatientIoOperations.java
src/test/java/org/isf/patient/test/TestPatient.java
src/test/java/org/isf/patient/test/Tests.java

Found out that the `@Transient weight` property in `Patient` entity was used only (1 occurrence) in `WardPharmacyNew`, while `@Transient height` property never used.
Going to simplify Patient’s entity and to retrieve his/her weight only when needed.

Op 262 contextualize weight and height

---

src/main/java/org/isf/serviceprinting/manager/PrintReceipt.java

In the logging statement the else clause is reached only when `defaultPrinterService` is null.   Attempting to `toString()` on a null value results in a NPE.  Just removed the statement as the other logging statement indicates the problem.
Found with SpotBugs.

Chore: Remove NPE in logging statement

---

src/main/java/org/isf/hospital/manager/HospitalBrowsingManager.java
src/main/java/org/isf/lab/manager/LabManager.java
src/main/java/org/isf/lab/manager/LabRowManager.java
src/test/java/org/isf/hospital/test/Tests.java
src/test/java/org/isf/lab/test/TestLaboratory.java
src/test/java/org/isf/lab/test/Tests.java

I could not get 100% coverage of `LabManager` because the private field `materialHashMap` was not accessible through Java reflection as I've done in other packages.   The reason is that the `@Transactional` annotation is used on two methods causing the class to generate a proxy class to handle the rollback.  So when I tried to `getDefinedFields` through reflection all I got was the proxy class methods and not the protected fields in the base class.  I tried a few options like `getSuperClass()` where I could get the variable but not set it to any new value.  Thus only 98% coverage for that class.

OP-383 increase coverage Hospital and Lab; reformat managers

---

src/main/java/org/isf/dlvrrestype/manager/DeliveryResultTypeBrowserManager.java
src/main/java/org/isf/dlvrtype/manager/DeliveryTypeBrowserManager.java
src/test/java/org/isf/dlvrrestype/test/Tests.java
src/test/java/org/isf/dlvrtype/test/Tests.java

Add tests to increase coverage and formatter `Manager` files to match standards.
All tests pass locally.

OP-381 increase coverage for dlvrestype and dlvrtype packages

---

src/main/java/org/isf/exa/manager/ExamBrowsingManager.java
src/main/java/org/isf/exa/manager/ExamRowBrowsingManager.java
src/main/java/org/isf/exa/service/ExamRowIoOperations.java
src/main/java/org/isf/examination/manager/ExaminationBrowserManager.java
src/main/java/org/isf/exatype/manager/ExamTypeBrowserManager.java
src/test/java/org/isf/exa/test/Tests.java
src/test/java/org/isf/examination/test/Tests.java
src/test/java/org/isf/exatype/test/Tests.java

Increase test coverage for `exa`, `examination` and `exatype` packages.
Also reformat `Manager` classes to meet project standards and remove unused `logger` variables.
All tests pass locally.

OP-382 Increase coverage and format Manager files

---

src/main/java/org/isf/opetype/manager/OperationTypeBrowserManager.java
src/test/java/org/isf/opetype/test/Tests.java

Also fixed an NPE in `validateOperationType()` if the key value was null.

OP-397 increase coverage in opetype; format Manager file

---

pom.xml

Current address is secure: https://www.dcm4che.org/maven2/

Chore: update Dcm4Che Repository address to use https

---

src/test/java/org/isf/visits/test/Tests.java

I was reviewing the PR for OP-404 and noticed a spelling mistake and that two tests were duplicated.  This PR fixes the spelling and removes the duplicated tests.

OP-404 update: remove duplicated tests and fix spelling

---

src/test/java/org/isf/admission/test/Tests.java
src/test/java/org/isf/admtype/test/Tests.java
src/test/java/org/isf/agetype/test/Tests.java
src/test/java/org/isf/disctype/test/Tests.java
src/test/java/org/isf/disease/test/Tests.java
src/test/java/org/isf/distype/test/Tests.java
src/test/java/org/isf/dlvrtype/test/Tests.java
src/test/java/org/isf/exa/test/Tests.java
src/test/java/org/isf/examination/test/Tests.java
src/test/java/org/isf/lab/test/Tests.java

This was found with SpotBugs.
The issue: Method invokes inefficient `new String(String)` constructor
Rationale: Using the` java.lang.String(String)` constructor wastes memory because the object so constructed will be functionally indistinguishable from the String passed as a parameter.  Just use the argument String directly.
I am ashamed to say that it was I who originally added the code being changed; I realized my mistake about half way through adding the new tests.

Chore: remove inefficient new String() constructor

---

src/main/java/org/isf/medicalstock/service/MedicalStockIoOperations.java
src/main/java/org/isf/opd/service/OpdIoOperationRepositoryImpl.java
src/main/java/org/isf/opd/service/OpdIoOperations.java
src/main/java/org/isf/patvac/service/PatVacIoOperations.java
src/test/java/org/isf/medicalstock/test/TestLot.java
src/test/java/org/isf/medicalstock/test/TestMovement.java
src/test/java/org/isf/medicalstock/test/Tests.java

These instances were found using IntelliJ's Analyze plugin looking for unused import statements.

Chore: remove unused imports

---

src/main/java/org/isf/therapy/manager/TherapyManager.java
src/main/java/org/isf/therapy/model/Therapy.java
src/main/java/org/isf/therapy/service/TherapyIoOperations.java
src/test/java/org/isf/therapy/test/Tests.java

While writing a test for `public ArrayList<Medical> getMedicalsOutOfStock(ArrayList<Therapy> therapies) ` in `org.isf.therapy.manager.TherapyManager` there was a NPE generated.  The reason was that the method started off with
````
public ArrayList<Medical> getMedicalsOutOfStock(ArrayList<Therapy> therapies) throws OHServiceException {
MovWardBrowserManager wardManager = new MovWardBrowserManager();
MedicalBrowsingManager medManager = new MedicalBrowsingManager();
````
Both `wardManager` and `medManager` should be `@Autowired` instead of constructing new instances as they were written the calls made in the managers to the `service` level  generated NPE.   To fix the NPEs both lines were removed and the `managers` were instead `@Autowired`.

OP-412 increase coverage in therapy; format Manager file; fix NPE

---

src/main/java/org/isf/sms/service/SmsSenderGSM.java
src/main/java/org/isf/stat/manager/JasperReportsManager.java

There is no need to call `toString()` on a field/variable that is already a `String` type.
See OP-423.
Found with IntelliJ's Analyze plugin looking for redundant code.

OP-423 remove unneeded toString()

---

src/main/java/org/isf/utils/db/CSV2SQL.java
src/main/java/org/isf/utils/db/ImportTranslatedProperties.java
src/main/java/org/isf/utils/db/UTF8Control.java
src/main/java/org/isf/utils/excel/ExcelExporter.java

Replace constant charset String literal  (like "UTF-8")  with a predefined Charset object like StandardCharsets.UTF_8. This may work a little bit faster, because charset lookup becomes unnecessary.
Found with IntelliJ's Analyze plugin.

Chore: Use StandardCharsets.UFT_8

---

src/main/java/org/isf/utils/exception/OHException.java

Just use the ` void error(String var1, Throwable var2);` method of the `org.slf4j.Logger` class.
Found with IntelliJ's Analyze plugin

Chore: Logger placeholder not available for `cause`

---

src/main/java/org/isf/sms/service/SmsSenderGSM.java

Use more efficient parameterized logging message instead of concatenation; this was just introduced with a recent push.

Chore: use parameterized logging message instead of concatenation

---

src/test/java/org/isf/patient/TestMergePatient.java

Maven selects files that start with "Test" as files to look inside for tests; had to rename this file.

Chore: rename file so maven knows it has tests in it

---

src/main/java/org/isf/patvac/manager/PatVacManager.java
src/main/java/org/isf/patvac/model/PatientVaccine.java
src/test/java/org/isf/patvac/test/Tests.java

Also improvements to `equals()` routine to handle more `null` cases.

OP-439 Increase coverage and format Model file

---

src/main/java/org/isf/opd/manager/OpdBrowserManager.java
src/main/java/org/isf/opd/model/Opd.java
src/test/java/org/isf/opd/test/TestOpd.java
src/test/java/org/isf/opd/test/Tests.java

Use parameterized testing method for OPDEXTENDED with `true` and `false` values.

OP-433 set OPDEXTENDED true and false and increase coverage

---

src/test/resources/log4j.properties

Add `log4.properties` to `test/resources` so the testing code doesn't complain about misconfigured log4j statements

Chore: add log4.properties file to test/resources

---

src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java

No need to test for `null` because `instanceOf` always returns `false` for a `null` value.
Found with SpotBugs.

Chore instanceOf returns false for null

---

src/main/java/org/isf/utils/time/TimeTools.java
src/test/java/org/isf/utils/time/TestTimeTools.java

See OP-450.
In addition did a few other small cleanups:
- Format the file
- Use character type for single length string
- Remove unused import
- Remove unused main routine now covered by tests
- Add private constructor given all methods are static
- Use base **Calendar** class instead of **GregorianCalendar** class
- Extract common date pattern to class constant
- Given the TimeTools file is fixed via OP-450, remove the `@Ignore` directives in the test file

OP-450 fix getDaysBetweenDate() and parseDate()

---

src/main/java/org/isf/exa/service/ExamRowIoOperations.java
src/test/java/org/isf/exa/test/Tests.java

Remove deprecated `getExamrows` method.    The method is not used in GUI and the API project uses the non-deprecated version: `getExamRows`.
Changed the test code to use `getExamRows`.

Chore remove deprecated method: getExamrows

---

src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperationRepositoryImpl.java

With refactoring the public class has the same method signature as the one being called thus the need for the second method is moot.
In the process reordered the imports correctly, used `StringUtils.isEmpty()` and other minor improvements.   All the core tests pass after the change.

Chore: refactoring makes indirection not needed

---

src/main/java/org/isf/utils/file/FileTools.java

In addition did a few other small cleanups:
- Use diamond notation
- Specify array size
- Use primitive data type instead of wrapper class
- Use character type for single length string

Chore: fix specification of parameter in log message

---

src/main/java/org/isf/stat/manager/JasperReportsManager.java

I did some debugging, and it looks like the thread is in waiting state because of
at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1414)
After some googling, it looks like this comment from SO describes why it happens: https://stackoverflow.com/a/14108717
So, most probably, the Connection object leak.
I added a close connection operation in generateJasperReport, 
After running the application with this change I cannot reproduce the bug, but I'm not 100% sure as it reproduced previously from time to time.

OP-251 Close connection after opening it. Fixes Connection leak.

---

src/test/java/org/isf/dicom/test/Tests.java
src/test/java/org/isf/disease/test/Tests.java
src/test/java/org/isf/medicals/test/Tests.java
src/test/java/org/isf/medicalstock/test/Tests.java
src/test/java/org/isf/medicalstockward/test/Tests.java
src/test/java/org/isf/medstockmovtype/test/Tests.java
src/test/java/org/isf/medtype/test/Tests.java
src/test/java/org/isf/menu/test/Tests.java
src/test/java/org/isf/opd/test/Tests.java
src/test/java/org/isf/operation/test/Tests.java
src/test/java/org/isf/opetype/test/Tests.java
src/test/java/org/isf/patient/test/Tests.java
src/test/java/org/isf/patvac/test/Tests.java
src/test/java/org/isf/pregtreattype/test/Tests.java
src/test/java/org/isf/priceslist/test/Tests.java
src/test/java/org/isf/pricesothers/test/Tests.java
src/test/java/org/isf/supplier/test/Tests.java
src/test/java/org/isf/therapy/test/Tests.java
src/test/java/org/isf/vaccine/test/Tests.java
src/test/java/org/isf/vactype/test/Tests.java
src/test/java/org/isf/visits/test/Tests.java
src/test/java/org/isf/ward/test/Tests.java

Minor changes to use consistent and more natural **assertj** syntax across the tests.   Some of this style was adopted with the later tests and this PR goes back and makes the style consistent.

Chore: use more natural assertj syntax

---

src/main/java/org/isf/therapy/manager/TherapyManager.java

This is a performance improvement.
Found with IntelliJ Analyze plugin.

Chore: use primitive type instead of class object

---

src/test/java/org/isf/accounting/test/Tests.java
src/test/java/org/isf/admission/test/Tests.java
src/test/java/org/isf/admtype/test/Tests.java
src/test/java/org/isf/agetype/test/Tests.java
src/test/java/org/isf/disctype/test/Tests.java
src/test/java/org/isf/disease/test/Tests.java
src/test/java/org/isf/distype/test/Tests.java
src/test/java/org/isf/dlvrrestype/test/Tests.java
src/test/java/org/isf/dlvrtype/test/Tests.java
src/test/java/org/isf/exa/test/Tests.java
src/test/java/org/isf/examination/test/Tests.java
src/test/java/org/isf/exatype/test/Tests.java
src/test/java/org/isf/hospital/test/Tests.java
src/test/java/org/isf/lab/test/Tests.java
src/test/java/org/isf/malnutrition/test/Tests.java
src/test/java/org/isf/menu/test/Tests.java

This is the second (and final) part (previous PR #363) of minor changes to use consistent and more natural assertj syntax across the tests. Some of this style was adopted with the later tests and this PR goes back and makes the style consistent.

Chore: use more natural assertj syntax (part 2)

---

pom.xml

Same version change as dependabot PRs in [GUI](https://github.com/informatici/openhospital-gui/pull/454) and [API](https://github.com/informatici/openhospital-api/pull/114) projects.

Chore: update license plugin version to match gui and api projects

---

src/main/java/org/isf/utils/validator/EmailValidator.java
src/test/java/org/isf/utils/validator/TestEmailValidator.java

See OP-473
The current validation routine simplifies the regex by making the matcher case-insensitive but changes nothing else (than formatting).  Given this setup all the new accompanying tests pass as the system currently exists.
Given the note in OP-473, there is a suggested alternative regex that make the tests in `testQuestionablePatterns` fail (as I think they should).

Op 473 email validation regex

---

src/main/java/org/isf/patient/manager/PatientBrowserManager.java
src/main/java/org/isf/patient/service/PatientIoOperationRepository.java
src/main/java/org/isf/patient/service/PatientIoOperationRepositoryImpl.java
src/main/java/org/isf/patient/service/PatientIoOperations.java
src/test/java/org/isf/patient/test/Tests.java

The aim of this implementation is to add **basic search capabilities** on patient entity to support OH 20 UI requirements (https://openhospital.atlassian.net/browse/OP-323).
At the moment, supported search parameters are:
- birthdate
- address
- firstName
- secondName
This is [the first of two PR](https://openhospital.atlassian.net/browse/OP-487): the second one will be [on the oh-api project](https://openhospital.atlassian.net/browse/OP-489), but it _depends_ on this one.

OP-488 Implement patient search in oh-core

---

src/main/java/org/isf/patient/service/PatientIoOperationRepositoryImpl.java
src/main/java/org/isf/patient/service/PatientIoOperations.java
src/test/java/org/isf/patient/test/Tests.java

Replace type specification and use diamond notation that is available starting with Java 7.
Note:  this is in code pushed earlier today.

Chore: use diamond notation

---

src/main/java/org/isf/dicom/manager/FileSystemDicomManager.java
src/main/java/org/isf/examination/manager/ExaminationBrowserManager.java
src/main/java/org/isf/lab/manager/LabManager.java
src/main/java/org/isf/medicalstockward/manager/MovWardBrowserManager.java
src/main/java/org/isf/operation/manager/OperationBrowserManager.java

Starting with JDK 8 `Collections.sort()` internally calls `List.sort()`.  To save an extra method call just use `List.sort()` directly.
Found with IntelliJ Analyze plugin.

Chore: use List.sort() instead of Collections.sort()

---

src/main/java/org/isf/generaldata/ConfigurationProperties.java
src/main/java/org/isf/generaldata/ExaminationParameters.java
src/main/java/org/isf/generaldata/GeneralData.java
src/main/java/org/isf/generaldata/SmsParameters.java
src/main/java/org/isf/generaldata/TxtPrinter.java
src/main/java/org/isf/generaldata/Version.java
src/main/java/org/isf/generaldata/XmppData.java

In order to prevent configuration methods and properties ovverride, all configuration classes are modified as final

Make configuration classes final as security pattern

---

pom.xml

Updates license-maven-plugin from 4.0 to 4.1 to match dependabot change to GUI and API projects.

Chore: Bump license.maven.plugin.version from 4.0 to 4.1

---

src/main/java/org/isf/admission/service/AdmissionIoOperations.java

Set the end of the day range to the next day as the SQL code checks all parts of the date/time; currently it is set to June30, 0 minutes, 0 seconds thus anything occurring on June 30 is not retrieved in the search.  Setting it to July 1 makes it look like midnight on June 30 instead of 1 second into the day.

Chore: set date to next day

---

src/main/java/org/isf/generaldata/MessageBundle.java

For MessageFormat to produce a single quote it must be escaped in the original pattern.   So as not to have everybody remember to escape it, just do it in code.

Chore: escape single quotes

---

src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java

Remove null check of variable `movement` as it was previously dereferenced a few lines (line 126) above.
Found with SpotBugs.

Chore: nullcheck of movement when variable previously dereferenced

---

src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java
src/test/java/org/isf/medicalstock/test/Tests.java

The `getSupplier()` and `getWard()` will always return on object of the correct type or the value `null`.  The test should be for `null` indicating that a supplier or ward must be selected.

Chore: fix if test

---

src/main/java/org/isf/accounting/manager/BillBrowserManager.java
src/main/java/org/isf/accounting/service/AccountingIoOperations.java
src/main/java/org/isf/accounting/service/AccountingPatientMergedEventListener.java
src/main/java/org/isf/admission/manager/AdmissionBrowserManager.java
src/main/java/org/isf/admission/service/AdmissionIoOperationRepositoryCustom.java
src/main/java/org/isf/admission/service/AdmissionIoOperations.java
src/main/java/org/isf/admission/service/AdmissionPatientMergedEventListener.java
src/test/java/org/isf/accounting/test/TestBill.java
src/test/java/org/isf/accounting/test/TestBillItems.java
src/test/java/org/isf/accounting/test/TestBillPayments.java
src/test/java/org/isf/accounting/test/Tests.java
src/test/java/org/isf/admission/test/TestAdmission.java
src/test/java/org/isf/admission/test/Tests.java

The primary purpose of this PR is to remove unneeded `throws OHServiceException` clauses in the `accounting` and `admission` packages.
In the process other smaller changes where made like simplifying methods, inlining single line private methods into the single calling routine, some formatting, and other related removal of code smells.
All the Core junit tests pass after these changes.
When this PR is committed it will cause compile errors in the GUI project for which I'm going to submit another PR.

Chore: code cleanup; remove unneeded throws clauses

---

src/main/java/org/isf/dicomtype/manager/DicomTypeBrowserManager.java

See OP-742; correct a cut-n-paste error; there are no `vaccines` in the `dicom` package.

OP-742: fix method name to match the object in the package

---

src/main/java/org/isf/utils/excel/ExcelExporter.java
src/main/java/org/isf/utils/file/FileTools.java
src/test/java/org/isf/therapy/test/Tests.java

Array initializers can omit the type because it is already specified in the left side of the assignment.

Chore: remove redundant 'new' expression in constant array creation

---

src/main/java/org/isf/stat/manager/JasperReportsManager.java
src/main/java/org/isf/utils/time/TimeTools.java
src/test/java/org/isf/utils/time/TestTimeTools.java

See OP-751
- add missing `convertToLegacyFormatForLibWithoutJavaTimeSupport()` method calls
- fix date patterns
- change method parameter from `false` to `true` when there was no time component

OP-751 fix date conversions in reports

---

src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperationRepositoryImpl.java
src/main/java/org/isf/patient/manager/PatientBrowserManager.java
src/main/java/org/isf/patvac/manager/PatVacManager.java
src/main/java/org/isf/pregtreattype/manager/PregnantTreatmentTypeBrowserManager.java
src/main/java/org/isf/priceslist/manager/PriceListManager.java
src/main/java/org/isf/pricesothers/manager/PricesOthersManager.java

The easiest change is to use `isEmpty()` from `org.apache.commons.lang3` which is already included in the project and used in some of the code.
Also changed a few `!isEmpty()` to `isNotEmpty()`.

Chore Starting with Spring 5.3.0, isEmpty() was deprecated.

---

pom.xml
src/test/java/org/isf/therapy/test/Tests.java
src/test/resources/database.properties

[H2 v2.0 changelog ](https://github.com/h2database/h2database/releases/tag/version-2.0.202)- TLDR: they fixed lots of bugs
Additional changes to make the upgrade work:
- add `NON_KEYWORDS=USER` - workaround to use `USER` as table name even if it's a keyword in H2 (see [this explanation](https://github.com/h2database/h2database/issues/3363#issuecomment-1010631797))
- fixed `testTherapyRowToString` - that test (added in https://github.com/informatici/openhospital-core/commit/025b642f92ebdadd5f7cc78e435ab5af8967059a ) was failing also when executing it individually with H2 v1. When executing it with all the other tests it was passing, due, most probably, to some race condition bug in H2 v1.x that has been fixed in v2.x
replaces #580

chore: bump h2 dependency to v2.x

---

pom.xml

Combined all the recent buildbot updates and tested them together
- Had to add `commons-lang3` dependency because jasperreports 6.19.0 removed it 
- Reorder some dependencies so the latest version of common jars where used and not excluded
- Change `slf4j-log4j12` to `slf4j-reload4j` which is the new name; see `Reload4j 1.2.18 as a replacement for log4j 1.2.17` at https://www.slf4j.org/log4shell.html
I will rebase/close the buildbot entries when this is committed.

Chore: combine and fix recent buildbot updates

---

pom.xml

Combine and test recent dependabot suggested upgrades as a single unit. This fixes a RCE CVE in Spring too.
Found that Hibernate has an issue; see https://github.com/informatici/openhospital-core/pull/627#issuecomment-1089072632
I will update all the individual PRs once this is committed.
This PR updates H2, Spring Framework, Spring Boot, Spring Data JPA, maven compiler plugin, metadata-extractor, poi, and poi-ooxml

Chore: combine and fix recent buildabot updates

---

src/main/java/org/isf/generaldata/GeneralData.java

added USERSLISTLOGIN variable to GeneralData file to login by typing the username in a textbox (no) or selecting the user from a list (yes) (See OP-705)

OP-705 Add possibility to login by typing the username instead of selecting from a list

---

src/main/java/org/isf/medicalstock/service/MovementIoOperationRepositoryImpl.java

See OP-946
Corrects a cut-n-paste error as the fields tested are not the ones used in the query.

OP-946 Fix IllegalArgumentException in Pharmaceutical Stock

---

src/main/java/org/isf/visits/manager/VisitManager.java
src/test/java/org/isf/ward/test/TestWard.java
src/test/java/org/isf/ward/test/Tests.java

See OP-939
Added validation for ward with no beds and for mismatch between patient's sex and ward type.
There is a corresponding GUI PR that implements the visual changes.

 OP-939 add additional validation logic for visit

---

src/main/java/org/isf/utils/excel/ExcelExporter.java

This is the hotfix version.
See [OP-947](https://openhospital.atlassian.net/browse/OP-947)
While working on [OP-943](https://openhospital.atlassian.net/browse/OP-943) I realized that the OLD format needed the same column count parameter. Originally I had deleted all the OLD methods until I noticed [OP-943](https://openhospital.atlassian.net/browse/OP-943). I forgot to go back and make the column change.

OP-947 do not export the button object to Excel file (old format)

---

src/main/java/org/isf/accounting/model/Bill.java
src/main/java/org/isf/accounting/model/BillPayments.java
src/main/java/org/isf/accounting/service/AccountingIoOperations.java
src/main/java/org/isf/admission/model/Admission.java
src/main/java/org/isf/admission/service/AdmissionIoOperations.java
src/main/java/org/isf/dicom/model/FileDicom.java
src/main/java/org/isf/examination/model/PatientExamination.java
src/main/java/org/isf/lab/model/Laboratory.java
src/main/java/org/isf/lab/service/LabIoOperations.java
src/main/java/org/isf/malnutrition/model/Malnutrition.java
src/main/java/org/isf/medicalstock/model/Lot.java
src/main/java/org/isf/medicalstock/model/Movement.java
src/main/java/org/isf/medicalstock/service/MedicalStockIoOperations.java
src/main/java/org/isf/medicalstockward/model/MovementWard.java
src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java
src/main/java/org/isf/opd/model/Opd.java
src/main/java/org/isf/operation/model/OperationRow.java
src/main/java/org/isf/patvac/model/PatientVaccine.java
src/main/java/org/isf/patvac/service/PatVacIoOperationRepositoryImpl.java
src/main/java/org/isf/patvac/service/PatVacIoOperations.java
src/main/java/org/isf/sms/manager/SmsManager.java
src/main/java/org/isf/sms/model/Sms.java
src/main/java/org/isf/sms/service/SmsOperations.java
src/main/java/org/isf/therapy/manager/TherapyManager.java
src/main/java/org/isf/therapy/model/TherapyRow.java
src/main/java/org/isf/utils/time/RememberDates.java
src/main/java/org/isf/utils/time/TimeTools.java
src/main/java/org/isf/visits/model/Visit.java

See OP-968
Some might consider these changes excessive and unneeded but given the many sources of where the values are coming from these changes ensure everything is consistent.
Added a new method `TimeTools.truncateToSeconds()` that does what the method name implies but also checks for null values.

OP-968 truncate DateTime values to seconds when storing in model and in service level

---

pom.xml

See OP-831
Tried to upgrade everything to the latest mariadb versions (connector, Hibernate dialect, etc.) but ran into problems.  This includes `org.isf.utils.db.DbSingleConn` which imports a class from the mysql jar: `import com.mysql.cj.jdbc.exceptions.CommunicationsException;`.   I think this can be removed by catching the `SQLException` and `IOException`, printing the message, and rethrowing them but I ran into issues about failing to connect to the DB.  I don't think it had to do with these changes.   
Given this class was written in 2005 I wonder if there are better alternatives for the DB connection code. :smirk:

OP-831 upgrade to java-mysql-connector 8.0.31

---

pom.xml

See OP-831
Tried to upgrade everything to the latest mariadb versions (connector, Hibernate dialect, etc.) but ran into problems.  This includes `org.isf.utils.db.DbSingleConn` which imports a class from the mysql jar: `import com.mysql.cj.jdbc.exceptions.CommunicationsException;`.   I think this can be removed by catching the `SQLException` and `IOException`, printing the message, and rethrowing them but I ran into issues about failing to connect to the DB.  I don't think it had to do with these changes.   
Given this class was written in 2005 I wonder if there are better alternatives for the DB connection code. :smirk:

OP-831 use the new maven dependency format for the jar

---

pom.xml

The Springframework  update fixes the following CVEs:
- [cve-2023-20860: Security Bypass With Un-Prefixed Double Wildcard Pattern](https://spring.io/security/cve-2023-20860)
- [cve-2023-20861: Spring Expression DoS Vulnerability](https://spring.io/security/cve-2023-20861)
All the tests ran successfully in the IDE and with `mvn clean test`

Chore: combine recent dependabot updates into single PR for testing

---

src/main/java/org/isf/priceslist/service/PricesListIoOperations.java

`priceRepository.findByList_id(list.getId());` returns a `List<Prices>`; no need to cast it again

Chore: remove redundant type cast

---

src/main/java/org/isf/sms/providers/gsm/GSMGatewayService.java

Exception tracebacks in logger call do not use a placeholder

Chore: mismatched number of placeholders in logger call

---

pom.xml

Release Notes:  https://github.com/spring-projects/spring-framework/releases/tag/v5.3.27
This update fixes the following CVE:
[cve-2023-20863: Spring Expression DoS Vulnerability](https://spring.io/security/cve-2023-20863)

Chore: update to Spring 5.3.27

---

src/main/java/org/isf/generaldata/GeneralData.java

See OP-897
BTW, I reset the default value for STRONGLENTH to the value specified in the JIRA for OP-894.  I'll fix the doc with the changes for this issue are made.

OP-897 use value of zero to turn off password retries checking

---

pom.xml

Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.11
Updated one dependency that is in Core project (mysql)
This release includes a fix for [CVE-2023-20873: Security Bypass With Wildcard Pattern Matching on Cloud Foundry](http://spring.io/security/cve-2023-20873).

Chore: Upgrade to Spring Boot 2.7.11

---

pom.xml

Combine updates for jackson-annotations, jackson-modules-java8, jasperreports, spring-data-jpa and junit together for testing.
`mvn clean test` was successful as was running the tests in IntelliJ

Chore: combine recent dependabot updates together for testing

---

src/main/java/org/isf/utils/exception/model/OHExceptionMessage.java

It was probably a typo when the new constructor was created as the only place where it is being used is where ErrorDescription.PASSWORD_TOO_SHORT is passed as description.
I verfified that constructor is not used anywhere else in openhospital-core, openhospital-api or openhospital-gui, so no other code is affected.

OP-1067 OHExceptionMessage: Description should come from the argument and not be hardcoded

---

src/main/java/org/isf/patient/manager/PatientBrowserManager.java
src/test/java/org/isf/patient/test/Tests.java

See OP-1083
Rebuilt Core and then successfully rebuilt GUI.    There are corresponding changes required in API repo that in addition fix some "FIXME" comments

OP-1083: remove deprecated method from org.isf.patient.manager.PatientBrowserManager

---

src/main/java/org/isf/accounting/service/AccountingIoOperations.java
src/test/java/org/isf/accounting/test/Tests.java

See OP-1088
Removed methods, rebuilt the jar, ran the unit tests successfully.
Used new jar to rebuild GUI and API without errors. Ran all the API tests successfully.

OP-1088 Remove deprecated methods from org.isf.accounting.service.AccountingIoOperation

---

src/main/java/org/isf/accounting/manager/BillBrowserManager.java
src/test/java/org/isf/accounting/test/Tests.java

Removed methods, rebuilt the jar, ran the unit tests.
Used new jar to rebuild GUI and API without errors. Ran all the API tests successfully.
Note:
Had to change the body to allow for the parameter zero to get all payments as that is what is supported at the IO level of the code:
`public List<BillPayments> getPayments(int billID) throws OHServiceException`

OP-1087 Remove deprecated methods from org.isf.accounting.manager.BillBrowserManager

---

src/test/java/org/isf/admission/test/Tests.java
src/test/java/org/isf/dicom/test/TestFileSystemDicomManager.java
src/test/java/org/isf/dicom/test/TestSqlDicomManager.java
src/test/java/org/isf/dicom/test/Tests.java
src/test/java/org/isf/disease/test/Tests.java
src/test/java/org/isf/distype/test/Tests.java

Replace deprecated method usage in tests with more recent versions.
Rebuilt the CORE project and ran all the unit tests succesffully.

Chore: remove deprecated method usage

---

src/main/java/org/isf/medicalstockward/manager/MovWardBrowserManager.java
src/test/java/org/isf/medicalstockward/test/Tests.java

See OP-1090
Removed methods, rebuilt the jar, ran the unit tests.
Used new jar and rebuilt GUI and there were no issues.
Used new jar and rebuilt API and there were errors.   I commented out three methods that were causing problems.   I checked the UI code base and it appears that these "/medicalstockward" endpoints are not being used but only defined.   I left them in the API code for easier updating of the API and UI code bases but those more familiar with the UI.
See https://github.com/informatici/openhospital-api/pull/271

OP-1090 Remove deprecated methods from org.isf.medicalstockward.manager.MovWardBrowserManager

---

pom.xml

Combine all recent dependabot updates to Junit into a single PR.
Also removed a duplicate definition of the surefire plugin.
Ran `mvn clean test` without error.

Upgrade all junit dependencies

---

src/main/java/org/isf/stat/manager/JasperReportsManager.java

There is no need to use `toString()` as the concatenation implicitly does it.

Chore: remove unneeded toString()

---

src/main/java/org/isf/dicom/manager/FileSystemDicomManager.java
src/main/java/org/isf/xmpp/manager/Interaction.java

gets a small performance boast

Chore: use single character in String.indexOf() method

---

src/main/java/org/isf/generaldata/ConfigurationProperties.java

Specifying `final` on a `static` methods is redundant an the method can't be overridden anyway

Chore: remove `final` on static methods

---

src/main/java/org/isf/xmpp/manager/AbstractCommunicationFrame.java

Class is strange as it is an abstract class that extends from a concrete class which shouldn't be done.   And since it really is a GUI class it is in the wrong project IMHO.

Fix: restore class used in GUI

---

pom.xml

Combined 3 recent upgrades and ran all tests.   FWIW, the missing `dcm4che` maven artifacts now exist.
`mvn clean test` is successful.
I will close the individual PRs after this is merged.

Chore: combine recent dependabot upgrades

---

src/main/java/org/isf/admission/model/Admission.java
src/main/java/org/isf/anamnesis/model/PatientHistory.java
src/main/java/org/isf/permissions/model/GroupPermission.java
src/main/java/org/isf/permissions/model/Permission.java

Before Java 8, a container annotation was required as wrapper to use multiple instances of the same annotation. As of Java 8, this is no longer necessary. Instead, these annotations should be used directly without a wrapper, resulting in cleaner and more readable code.
All tests ran cleanly.

Chore: remove AttributeOverrides annotation

---

src/main/java/org/isf/malnutrition/service/MalnutritionIoOperation.java

The deprecated method `getById(code)` is now replaced by `getReferenceById(code)`.
Here is the Javadoc
<pre>
/**
* Returns a reference to the entity with the given identifier. Depending on how the JPA persistence provider is
* implemented this is very likely to always return an instance and throw an
* {@link javax.persistence.EntityNotFoundException} on first access. Some of them will reject invalid identifiers
* immediately.
*
* @param id must not be {@literal null}.
* @return a reference to the entity with the given identifier.
* @see EntityManager#getReference(Class, Object) for details on when an exception is thrown.
* @deprecated use {@link JpaRepository#getReferenceById(ID)} instead.
* @since 2.5
*/
@Deprecated
T getById(ID id);
</pre>

Chore: remove deprecated method

---

src/main/java/org/isf/menu/manager/UserBrowsingManager.java
src/main/java/org/isf/menu/service/MenuIoOperations.java
src/test/java/org/isf/menu/test/Tests.java

Started removing the unused `insert` parameter which was left over from 2015 when it was used to determine whether to close the DB connection.
Also noticed that the routines always returned `true` so there was no need to `and` the `result` from the calls.
Built the new jar and recompiled and tested GUI and API without error.

Chore: removed unused `insert` parameter

---

src/main/java/org/isf/utils/table/TableSorter.java

Originally was drawn to this method to replace the deprecated (since JDK9) items: `getModifiers()` and `InputEvent.SHIFT_MASK`.   When trying to test the changes I found that the method was never used.     Rebuilt the CORE jar without the method and then successfully built and tested the GUI and API repos.   So the final "change" is to remove the method.

Chore: remove unused method

---

src/main/java/org/isf/accounting/model/Bill.java
src/main/java/org/isf/examination/model/PatientExamination.java
src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java
src/main/java/org/isf/operation/model/OperationRow.java
src/main/java/org/isf/priceslist/manager/PriceListManager.java
src/test/java/org/isf/examination/test/TestPatientExamination.java
src/test/java/org/isf/examination/test/Tests.java
src/test/java/org/isf/malnutrition/test/Tests.java
src/test/java/org/isf/medicalstock/test/Tests.java
src/test/java/org/isf/medicalstockward/test/TestMovementWard.java
src/test/java/org/isf/medicalstockward/test/Tests.java
src/test/java/org/isf/operation/test/TestOperationRow.java
src/test/java/org/isf/operation/test/Tests.java
src/test/java/org/isf/priceslist/test/Tests.java

The code used a mixture of formats for numeric literals so changed them to the most common form which has a value after the period (`1.0` instead of `1.`) and lower case for the numeric type (`f` instead of `F` and `d` instead of `D`),

Chore: use consistent form for float and double literals

---

src/main/java/org/isf/opd/service/OpdIoOperationRepositoryImpl.java
src/main/java/org/isf/patient/service/PatientIoOperationRepositoryImpl.java
src/main/java/org/isf/patvac/service/PatVacIoOperationRepositoryImpl.java

There are two styles to convert a collection to an array:
- A pre-sized array, for example, c.toArray(new String[c.size()])
- An empty array, for example, c.toArray(new String[0])
In older Java versions, using a pre-sized array was recommended, as the reflection call necessary to create an array of proper size was quite slow.
However, since late updates of OpenJDK 6, this call was intrinsified, making the performance of the empty array version the same, and sometimes even better, compared to the pre-sized version. Also, passing a pre-sized array is dangerous for a concurrent or synchronized collection as a data race is possible between the size and toArray calls. This may result in extra nulls at the end of the array if the collection was concurrently shrunk during the operation.

Chore: remove pre-sized array

---

pom.xml

Release Notes:  https://github.com/spring-projects/spring-framework/releases/tag/v5.3.31

Chore: upgrade to Spring Framework 5.3.31

---

pom.xml

Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.18

Chore: upgrade to Spring Boot 2.7.18

---

src/main/java/org/isf/stat/manager/JasperReportsManager.java

The variable `patID` is already a `String`.

Chore: unnecessary String.valueOf()

---

src/test/java/org/isf/accounting/test/Tests.java
src/test/java/org/isf/examination/test/Tests.java
src/test/java/org/isf/visits/test/Tests.java

Fix tests that were not checking the Optional result of findById()

Chore: add test if present with findById() returning Optional

---

pom.xml

See OP-1163
Guess this is another reason to move to JDK 17 :smirk:

OP-1163 revert update to dcm4ch3 jars because of JDK17

---

pom.xml

Chore: make all the dcm4che jars the same level

---

src/main/java/org/isf/medicals/service/MedicalsIoOperations.java
src/main/java/org/isf/medicalstock/service/MovementIoOperationRepository.java

See OP-1202
The failure was caused by throwing an exception because the query result expects a single `Movement` and not a `List` of `Movement`s which is the case here.

OP-1202 Fix Pharmaceutical deletions error message

---

pom.xml

Update SpringBoot 3.2.5 and related dependencies 
Release Notes:  https://github.com/spring-projects/spring-boot/releases/tag/v3.2.5

Chore: update SpringBoot 3.2.5
