mysql/db/from_step_05.sql, mysql/db/step_56_enable_mvntbetwenwards.sql, rsc/database.properties, src/org/isf/medicalstock/model/Movement.java, src/org/isf/medicalstockward/manager/MovWardBrowserManager.java, src/org/isf/medicalstockward/model/MovementWard.java, src/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java, src/org/isf/medstockmovtype/manager/MedicaldsrstockmovTypeBrowserManager.java, src/org/isf/medstockmovtype/service/MedicalStockMovementTypeIoOperation.java, src/org/isf/medstockmovtype/service/MedicalStockMovementTypeIoOperationRepository.java
To add search fields in order to facilitate the search for diagnoses in the outpatient and admission forms
=> task OP-91, mvnt between wards

mysql/db/from_step_05.sql, mysql/db/step_57_multiple_operations in_admission.sql, src/org/isf/operation/manager/OperationBrowserManager.java, src/org/isf/operation/manager/OperationRowBrowserManager.java, src/org/isf/operation/model/OperationRow.java, src/org/isf/operation/model/Resultat.java, src/org/isf/operation/service/OperationIoOperationRepository.java, src/org/isf/operation/service/OperationIoOperations.java, src/org/isf/operation/service/OperationRowIoOperationRepository.java, src/org/isf/operation/service/OperationRowIoOperations.java
Interface modifications to consult the list of operations performed on a patient from his clinical cardboard
=> U2 g op 82 operations in clinical cardboard

mysql/db/from_step_05.sql, mysql/db/step_57_multiple_operations in_admission.sql, src/org/isf/operation/manager/OperationBrowserManager.java, src/org/isf/operation/manager/OperationRowBrowserManager.java, src/org/isf/operation/model/OperationRow.java, src/org/isf/operation/model/Resultat.java, src/org/isf/operation/service/OperationIoOperationRepository.java, src/org/isf/operation/service/OperationIoOperations.java, src/org/isf/operation/service/OperationRowIoOperationRepository.java, src/org/isf/operation/service/OperationRowIoOperations.java
Admission/Patient > Admission > Operation. modified and database modified to allow adding multiple operation to an admission.
=> Task OP-81 done (Uni2grow Cameroun)

src/org/isf/operation/manager/OperationRowBrowserManager.java, src/org/isf/operation/service/OperationRowIoOperationRepository.java, src/org/isf/operation/service/OperationRowIoOperations.java
U2 g op 82 operations in clinical cardboard
=> U2g op 82 operations in clinical cardboard

rsc/database.properties, src/org/isf/accounting/manager/BillBrowserManager.java, src/org/isf/accounting/service/AccountingBillIoOperationRepository.java, src/org/isf/accounting/service/AccountingBillPaymentIoOperationRepository.java, src/org/isf/accounting/service/AccountingIoOperations.java, src/org/isf/generaldata/GeneralData.java, src/org/isf/generaldata/MessageBundle.java, src/org/isf/patient/manager/PatientBrowserManager.java, src/org/isf/patient/service/PatientIoOperationRepository.java, src/org/isf/patient/service/PatientIoOperations.java, src/org/isf/stat/manager/JasperReportsManager.java
printing invoices list of open bill and allow patient's invoices summary
=> Op 84 & op 88: printing invoices list of open bill and allow patient's invoices summary

src/org/isf/malnutrition/manager/MalnutritionManager.java, src/org/isf/malnutrition/service/MalnutritionIoOperation.java, src/org/isf/malnutrition/service/MalnutritionIoOperationRepository.java, src/org/isf/medicals/manager/MedicalBrowsingManager.java, src/org/isf/medicals/service/MedicalsIoOperations.java, src/org/isf/medicalstock/service/MovementIoOperationRepositoryCustom.java, src/org/isf/medicalstockward/manager/MovWardBrowserManager.java, src/org/isf/medicalstockward/service/MedicalStockWardIoOperationRepositoryCustom.java, src/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java, src/org/isf/medicalstockward/service/MovementWardIoOperationRepository.java, src/org/isf/medstockmovtype/manager/MedicaldsrstockmovTypeBrowserManager.java, src/org/isf/medstockmovtype/service/MedicalStockMovementTypeIoOperation.java, src/org/isf/medtype/manager/MedicalTypeBrowserManager.java, src/org/isf/medtype/service/MedicalTypeIoOperation.java, src/org/isf/medtype/service/MedicalTypeIoOperationRepository.java, src/org/isf/menu/manager/UserBrowsingManager.java, src/org/isf/menu/service/GroupMenuIoOperationRepository.java, src/org/isf/menu/service/MenuIoOperations.java, src/org/isf/menu/service/UserGroupIoOperationRepository.java, src/org/isf/menu/service/UserIoOperationRepository.java, src/org/isf/menu/service/UserMenuItemIoOperationRepository.java
OP-111 Spring annotation for @Component, @Service and @Repository of M modules, organize imports #time 1h
=> OP-111 Spring annotation for @Component, @Service and @Repository

src/org/isf/examination/manager/ExaminationBrowserManager.java, src/org/isf/examination/service/ExaminationIoOperationRepository.java, src/org/isf/examination/service/ExaminationOperations.java, src/org/isf/exatype/manager/ExamTypeBrowserManager.java, src/org/isf/exatype/service/ExamTypeIoOperation.java, src/org/isf/exatype/service/ExamTypeIoOperationRepository.java, src/org/isf/hospital/service/HospitalIoOperations.java
=> Op 102 master refactoring for api

src/org/isf/sms/manager/SmsManager.java, src/org/isf/sms/service/SmsIoOperationRepository.java, src/org/isf/sms/service/SmsOperations.java, src/org/isf/sms/test/Tests.java, src/org/isf/supplier/manager/SupplierBrowserManager.java, src/org/isf/supplier/service/SupplierIoOperationRepository.java, src/org/isf/supplier/service/SupplierOperations.java, src/org/isf/supplier/test/Tests.java, src/org/isf/therapy/service/TherapyIoOperationRepository.java, src/org/isf/therapy/service/TherapyIoOperations.java, src/org/isf/therapy/test/Tests.java
=> OP-113 Spring annotation for @Component, @Service and @Repository

src/org/isf/admission/service/AdmissionIoOperations.java, src/org/isf/dicom/manager/FileSystemDicomManager.java, src/org/isf/dicom/manager/SourceFiles.java, src/org/isf/disease/manager/DiseaseBrowserManager.java, src/org/isf/disease/test/TestDiseaseContext.java, src/org/isf/examination/model/PatientExamination.java, src/org/isf/lab/manager/DateTextField.java, src/org/isf/lab/model/Laboratory.java, src/org/isf/lab/model/LaboratoryRow.java, src/org/isf/lab/test/TestLaboratory.java, src/org/isf/lab/test/TestLaboratoryRow.java, src/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java, src/org/isf/menu/service/MenuIoOperations.java, src/org/isf/operation/model/Operation.java, src/org/isf/operation/test/Tests.java, src/org/isf/patient/model/Patient.java, src/org/isf/patient/service/PatientIoOperationRepositoryImpl.java, src/org/isf/pregtreattype/test/Tests.java, src/org/isf/priceslist/test/Tests.java, src/org/isf/utils/table/TableSorter.java, src/org/isf/video/manager/LinuxVideoDevicesManager.java, src/org/isf/video/model/VideoDevice.java
This PR contains some of the cleanups from #46 which can be applied without changing the compilation target
=> Update to Java 6

pom.xml
https://openhospital.atlassian.net/browse/OP-178
=> OP-178 #comment fix validation-api version conflict between api #time 1h

pom.xml, src/org/isf/dicom/manager/DicomManagerFactory.java, src/org/isf/dicom/manager/FileSystemDicomManager.java
Fixed pom to manage the update of dicom libraries
=> Op 140 update dicom libraries

pom.xml
Version 1.2.1 cant be accessed from cytoscape repo anymore
=> OP-139: Upgrading to processing core 2.2.1

README.md, docker-compose.yml
Added informations to rebuild DB
=> Updated README to rebuild DB

src/org/isf/accounting/service/AccountingBillIoOperationRepository.java, src/org/isf/accounting/service/AccountingBillItemsIoOperationRepository.java, src/org/isf/accounting/service/AccountingBillPaymentIoOperationRepository.java, src/org/isf/accounting/service/AccountingIoOperations.java, src/org/isf/admission/service/AdmissionIoOperationRepository.java, src/org/isf/dicom/service/DicomIoOperationRepository.java, src/org/isf/dicom/service/DicomIoOperations.java, src/org/isf/disease/service/DiseaseIoOperationRepository.java, src/org/isf/disease/service/DiseaseIoOperations.java
Convert all native-SQL statement into HQL/JPQL (JPA Syntax) for modules from A to D
=> OP-129: Replace native SQL with JPQL (modules from A to D)

pom.xml, src/org/isf/serviceprinting/manager/PrintLabels.java
=> ADWA_6_print labels buttons added

src/org/isf/medicalstock/manager/MovStockInsertingManager.java, src/org/isf/medicalstock/model/Lot.java, src/org/isf/medicalstock/service/MedicalStockIoOperations.java, src/org/isf/medicalstock/test/Tests.java
Fixed discharge in pharmacy using AUTOMATICLOT=yes
=> Op 207 automaticlot not working

src/org/isf/dicom/manager/SourceFiles.java
the com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReader
provided by dcm4che library was unstable
=> Forced to use com.sun.imageio.plugins.jpeg.JPEGImageReader

src/main/java/org/isf/accounting/manager/BillBrowserManager.java, src/main/java/org/isf/exa/manager/ExamBrowsingManager.java, src/main/java/org/isf/lab/manager/LabManager.java, src/main/java/org/isf/utils/db/DbQuery.java, src/main/java/org/isf/utils/excel/ExcelExporter.java
Fix Java doc: `@Deprecated` -> `@deprecated`
Add missing `@Deprecated` annotation
=> Correct @Deprecated usage

src/main/java/org/isf/accounting/manager/BillBrowserManager.java, src/main/java/org/isf/lab/service/LabIoOperations.java, src/main/java/org/isf/therapy/manager/TherapyManager.java, src/main/java/org/isf/visits/manager/VisitManager.java
- Add missing `@Deprecated` annotation
- Correct method name and public variable links/code
- Remove 3 `@param` arguments that don't exist in the method signature
=> Minor JavaDoc updates

.ide-settings/idea/OpenHospital-code-style-configuration.xml
This is an update to this [PR](https://github.com/informatici/openhospital-core/pull/148l).   After I applied the formatting and import settings to the whole project I noted that some specific imports of packages were changed into wild card imports.  This corrects the oversight.
Sorry about the second push.
=> Update import settings for package imports

src/main/java/org/isf/dicom/manager/DicomManagerFactory.java, src/main/java/org/isf/dicom/manager/SourceFiles.java, src/main/java/org/isf/generaldata/MessageBundle.java, src/main/java/org/isf/sms/manager/SmsManager.java, src/main/java/org/isf/utils/db/DbSingleConn.java, src/main/java/org/isf/utils/file/FileTools.java, src/test/java/org/isf/lab/test/Tests.java
Fix modifiers are not in the canonical preferred order (as stated in the Java Language Specification).
This replaces this [PR](https://github.com/informatici/openhospital-core/pull/134).
Even though it looks like a lot of changes it really isn't as the files each were a mixture of spaces and tabs and I reformatted them all to tabs before applying the change.
=> Fix modifiers are not in the canonical preferred order

pom.xml, src/main/java/org/isf/admission/service/AdmissionIoOperationRepositoryImpl.java, src/main/java/org/isf/opd/service/OpdIoOperationRepositoryImpl.java, src/main/java/org/isf/patvac/service/PatVacIoOperationRepositoryImpl.java
Due to inactivity in #46 , I'm submitting this PR to have a minimal-impact switch to Java 8
=> Op-225 update to Java 8

README.md
Per the comment in this [PR](https://github.com/informatici/openhospital-core/pull/149) here are some quick and dirty instructions as to how to use the settings files for IntelliJ IDEA and Eclipse.
=> Document how to load style settings into IDEA and Eclipse

src/org/isf/vaccine/manager/VaccineBrowserManager.java, src/org/isf/vaccine/service/VaccineIoOperations.java, src/org/isf/vaccine/test/Tests.java
=> OP-242 Adding findVaccine(id) Functionality 

src/org/isf/vactype/manager/VaccineTypeBrowserManager.java, src/org/isf/vactype/service/VacTypeIoOperation.java, src/org/isf/vactype/test/Tests.java
=> OP-242 Adding findVaccineType(id) Functionality

pom.xml
=> Chore: bump slfj dependencies

src/org/isf/visits/manager/VisitManager.java, src/org/isf/visits/service/VisitsIoOperations.java, src/org/isf/visits/test/Tests.java
=> OP-242 Adding findVisit(id) Functionality

src/org/isf/ward/manager/WardBrowserManager.java, src/org/isf/ward/service/WardIoOperations.java, src/org/isf/ward/test/Tests.java
=> OP-242 Adding findWard(id) Functionality

src/main/java/org/isf/vaccine/manager/VaccineBrowserManager.java, src/main/java/org/isf/vaccine/service/VaccineIoOperations.java, src/main/java/org/isf/vactype/manager/VaccineTypeBrowserManager.java, src/main/java/org/isf/vactype/service/VacTypeIoOperation.java, src/main/java/org/isf/visits/manager/VisitManager.java, src/main/java/org/isf/visits/service/VisitsIoOperations.java, src/main/java/org/isf/ward/manager/WardBrowserManager.java, src/main/java/org/isf/ward/service/WardIoOperations.java, src/org/isf/ward/test/Tests.java, src/test/java/org/isf/vaccine/test/Tests.java, src/test/java/org/isf/vactype/test/Tests.java, src/test/java/org/isf/visits/test/Tests.java
Extend Module's Classes  to support findOne(id) method for recovering a single Object by ID
=>  OP-242  | Adding findOne(id) Functionality on CORE (Development Branch) for Several Modules

src/main/java/org/isf/utils/validator/EmailValidator.java, src/main/java/org/isf/ward/manager/WardBrowserManager.java
This is a code change to implement the validation for [OP-248](https://openhospital.atlassian.net/browse/OP-248)
If this pull request is approved, I will add the new email validation bundle messages in openhospital-gui ( https://github.com/informatici/openhospital-gui/pull/204 )
=> OP-248 Add Email Validation To Ward Edit Screen

src/main/java/org/isf/patient/manager/PatientBrowserManager.java, src/main/java/org/isf/patient/service/PatientIoOperations.java, src/main/java/org/isf/therapy/manager/TherapyManager.java, src/main/java/org/isf/visits/manager/VisitManager.java, src/test/java/org/isf/patient/test/Tests.java
R getPatient(name) -> getPatientByName(name) (deprecated)
R getPatient(code) -> getpatientById(code)
R isPatientPresent(name) -> isNamePresent(name) (manager)
R isPatientPresent(name) -> isPatientPresentByName(name) (service)
twins PRs:
- https://github.com/informatici/openhospital-api/pull/61
- https://github.com/informatici/openhospital-gui/pull/208
=> Some refactoring and deprecations

src/main/java/org/isf/patient/manager/PatientBrowserManager.java, src/main/java/org/isf/patient/service/PatientIoOperationRepository.java, src/main/java/org/isf/patient/service/PatientIoOperations.java
'PAT_AFFILIATED_PERSON' and 'PAT_IS_HEAD_AFFILIATION' are not defined
=> Removed unwanted method for not existing fields

src/org/isf/ward/manager/WardBrowserManager.java
=> OP-261 | Fix findWard name in WardBrowserManager

src/main/java/org/isf/accounting/service/AccountingBillIoOperationRepository.java
This was found during my adding of additional unit tests for [OP-249](https://openhospital.atlassian.net/jira/software/c/projects/OP/issues/OP-249).
=> OP-264 Changing b.id = :patID to b.patient.id = :patID

src/org/isf/vactype/manager/VaccineTypeBrowserManager.java
=> OP-268 | Fix findVaccineType name in VaccineTypeBrowserManager  

src/org/isf/visits/manager/VisitManager.java
=> OP-271 | Fix findVisit name in VisitManager

src/test/java/org/isf/accounting/test/TestBill.java, src/test/java/org/isf/accounting/test/TestBillItems.java, src/test/java/org/isf/accounting/test/TestBillPayments.java, src/test/java/org/isf/accounting/test/Tests.java
- Add tests for more coverage
- Use assertj
- Remove return statements in void methods
Coverage Before:
Coverage After:
=> OP-249 add Junit tests for accounting package

pom.xml
=> OP-294 | Fixing Testing Compilation Issue related to Checks Failing for PR#68 (API)

pom.xml, src/main/java/org/isf/stat/manager/JasperReportsManager.java, src/main/java/org/isf/utils/time/DateConverters.java, src/main/java/org/isf/utils/time/TimeTools.java
fixed erros caused by java time upgrade in reports module
=> [OP-282] reporting fix: workaround for LocalDateTime to Date conversion

src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java, src/main/java/org/isf/medicalstock/service/LotIoOperationRepository.java, src/main/java/org/isf/medicalstock/service/MedicalStockIoOperations.java
Fixed query to match expected behavior
TODO:
=> OP-345 misnamed method or bad query

src/main/java/org/isf/disctype/manager/DischargeTypeBrowserManager.java, src/test/java/org/isf/disctype/test/Tests.java
Locally 452 tests pass; 1 ignored, total tests: 453
=> OP-379 increase coverage of disctype package

src/main/java/org/isf/malnutrition/manager/MalnutritionManager.java, src/test/java/org/isf/malnutrition/test/Tests.java
Fixed some javadoc in manager class too.
=> OP-385 increase coverage Malnutrition; reformat manager

pom.xml, src/main/java/org/isf/admission/manager/AdmissionBrowserManager.java, src/test/java/org/isf/admission/test/TestAdmission.java, src/test/java/org/isf/admission/test/Tests.java, src/test/java/org/isf/ward/test/TestWard.java
=>  OP-373 Increase coverage of admission package

src/main/java/org/isf/medicals/manager/MedicalBrowsingManager.java, src/test/java/org/isf/medicals/test/Tests.java
=> OP-386 increase coverage Medicals; reformat manager

src/main/java/org/isf/medtype/manager/MedicalTypeBrowserManager.java, src/test/java/org/isf/medtype/test/Tests.java
=> OP-387 increase coverage Medtype; reformat manager file

src/main/java/org/isf/menu/manager/UserBrowsingManager.java, src/test/java/org/isf/menu/test/Tests.java
=> OP-394 increase coverage in menu package and reformat Manager file

src/main/java/org/isf/operation/manager/OperationBrowserManager.java, src/main/java/org/isf/operation/manager/OperationRowBrowserManager.java, src/test/java/org/isf/operation/test/TestOperationRow.java, src/test/java/org/isf/operation/test/Tests.java
=> OP-396 increase coverage in operation; format Manager files

src/main/java/org/isf/medicalstock/manager/MovBrowserManager.java, src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java, src/main/java/org/isf/medicalstock/model/Lot.java, src/main/java/org/isf/medicalstock/service/MedicalStockIoOperations.java, src/main/java/org/isf/medicalstockward/manager/MovWardBrowserManager.java, src/main/java/org/isf/medstockmovtype/manager/MedicaldsrstockmovTypeBrowserManager.java, src/test/java/org/isf/medicalstock/test/TestLot.java, src/test/java/org/isf/medicalstock/test/TestMovement.java, src/test/java/org/isf/medicalstock/test/Tests.java, src/test/java/org/isf/medicalstockward/test/Tests.java, src/test/java/org/isf/medstockmovtype/test/Tests.java
Every single line and method has not been covered because some of them were impossible to access.
I have already spent too many days getting the coverage that is here and fixing some of the code (typically NPEs or catching an exception and then immediately throwing it again when the method defines that exception as being part of the contract, etc.)
I did reformat the manager files and removed unused logger definitions.
This isn't perfect but it is better than when I started.
=> OP-392 increase coverage, format managers, and fix a few NPEs

src/main/java/org/isf/opd/service/OpdIoOperationRepositoryImpl.java, src/main/java/org/isf/opd/service/OpdIoOperations.java, src/main/java/org/isf/patvac/service/PatVacIoOperations.java, src/test/java/org/isf/opd/test/Tests.java, src/test/java/org/isf/patvac/test/Tests.java
See  https://openhospital.atlassian.net/browse/OP-395
=> OP-395 fix dateFrom and dateTo values

src/main/java/org/isf/visits/manager/VisitManager.java
Remove unused methods:
1. public ArrayList<Visit> getVisits(ArrayList<Visit> vsRows) 
2. public Visit createVisit(Visit vs)
3. private Visit createVisit(int visitID, Patient patient, Ward ward, GregorianCalendar date, String note, String duration, String service, boolean sms)
=> OP-403 remove unused methods: getVisits(), createVisit() [twice]

src/main/java/org/isf/supplier/manager/SupplierBrowserManager.java, src/test/java/org/isf/supplier/test/Tests.java
=> OP-401 increase coverage in supplier, format Manager file

src/main/java/org/isf/disease/manager/DiseaseBrowserManager.java, src/main/java/org/isf/disease/service/DiseaseIoOperations.java, src/main/java/org/isf/vaccine/manager/VaccineBrowserManager.java, src/main/java/org/isf/vaccine/service/VaccineIoOperations.java, src/test/java/org/isf/disease/test/Tests.java, src/test/java/org/isf/vaccine/test/Tests.java
OH-CORE fix For OP-408. OH-GUI fix to come as well.
=> OP-408 Fixing "The data has been updated by someone else”

src/main/java/org/isf/visits/manager/VisitManager.java, src/test/java/org/isf/visits/test/Tests.java
This is a replacement for the original [PR 291](https://github.com/informatici/openhospital-core/pull/291) as there were too many changes to the core files and the merge was done wrong.    There should now be 965 tests.
I am closing PR-291.
=> OP-404 increase coverage in visits; format Manager file

src/main/java/org/isf/utils/excel/ExcelExporter.java
When making the change to correct the compile error it appears that a line setting the font was deleted by mistake.
=> Update PR-293 by replacing missing line

src/main/java/org/isf/ward/manager/WardBrowserManager.java, src/test/java/org/isf/ward/test/TestWard.java, src/test/java/org/isf/ward/test/Tests.java
NOTE:  I had to fix the default email address used in setup() to be valid
=> OP-405 increase coverage in ward; format Manager file

src/main/java/org/isf/therapy/manager/TherapyManager.java
I was writing tests for the Therapy package and noticed that the method `deleteAllTherapies(Integer code)` was not working correctly.
I updated the method body without changing the method signature and my local tests now run cleanly.
This is a separate PR so the change doesn't get lost in the larger JUnit test suite to come.
=> OP-411 correct deleteAllTherapies() method

src/main/java/org/isf/pregtreattype/manager/PregnantTreatmentTypeBrowserManager.java, src/test/java/org/isf/pregtreattype/test/Tests.java
=> OP-398 increase coverage in pregtreattype; format Manager file

src/main/java/org/isf/dicomtype/manager/DicomTypeBrowserManager.java, src/test/java/org/isf/dicomtype/test/Tests.java
=> OP-406 increase coverage in dicomtype; format Manager file

src/test/java/org/isf/admission/test/TestAdmission.java, src/test/java/org/isf/lab/test/TestLaboratory.java, src/test/java/org/isf/lab/test/TestLaboratoryRow.java, src/test/java/org/isf/menu/test/TestUser.java
These instances were found using SpotBugs.
=> Chore: Remove field that is never read/used.

src/main/java/org/isf/exa/service/ExamRowIoOperations.java, src/main/java/org/isf/opd/manager/OpdBrowserManager.java, src/main/java/org/isf/opd/service/OpdIoOperations.java, src/main/java/org/isf/therapy/service/TherapyIoOperations.java, src/main/java/org/isf/utils/file/FileTools.java, src/main/java/org/isf/visits/manager/VisitManager.java, src/main/java/org/isf/visits/service/VisitsIoOperations.java
These instances were found using IntelliJ's Analyze plugin looking at those related to JavaDoc and DocLint.  In the process of examining the changes some punctuation and grammar changes were made too.   No code was touched.
=> Chore: JavaDoc fixes/improvements

src/main/java/org/isf/therapy/model/Therapy.java
Put back the empty constructor so the GUI code can compile.
=> OP-412 Undo removal of empty constructor

src/main/java/org/isf/examination/manager/ExaminationBrowserManager.java
Instead of enumerating the key set use `containsKey()` instead.
See OP-422.
Found with IntelliJ's Analyze plugin looking for redundant code.
=> OP-422 use containsKey()

src/main/java/org/isf/stat/manager/JasperReportsManager.java
Found with IntelliJ's Analyze plugin
=> Chore: Remove duplicated semicolon

src/main/java/org/isf/admission/service/AdmissionIoOperations.java, src/test/java/org/isf/admission/test/Tests.java
Use parameterized testing method for MATERNITYRESTARTINJUNE with `true` and `false` values.
=> OP-434 use parameterized tests for MATERNITYRESTARTINJUNE

src/main/java/org/isf/lab/manager/LabManager.java, src/test/java/org/isf/lab/test/TestLaboratory.java, src/test/java/org/isf/lab/test/Tests.java
Use parameterized testing method for LABEXTENDED and LABMULTIPLEINSERT  with all combinations of `true` and `false` values.
=> OP-435 tests with LABEXTENDED GeneralData

src/main/java/org/isf/operation/service/OperationIoOperationRepository.java, src/main/java/org/isf/operation/service/OperationIoOperations.java
Linked Bug in Jira: https://openhospital.atlassian.net/browse/OP-368
=> OP-368 Changes Operations list order in Prices Browser from Descending to Ascending

src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java
See OP-444 for description of the issue.
Also took the opportunity to reformat and improve the method.
This was found using SpotBugs.
=> OP-444 reorder code to avoid NPE

src/main/java/org/isf/serviceprinting/manager/PrintReceipt.java
=> Chore: use chained append() instead of concatenation in append

src/main/java/org/isf/operation/manager/OperationBrowserManager.java, src/main/java/org/isf/utils/excel/ExcelExporter.java, src/test/java/org/isf/dicom/test/TestSqlDicomManager.java, src/test/java/org/isf/medicalstock/test/Tests.java, src/test/java/org/isf/patient/test/Tests.java
=> OP-446 remove unused imports

src/main/java/org/isf/dicom/manager/SourceFiles.java
=> OP-448 remove pointless booleans

src/main/java/org/isf/utils/file/FileTools.java, src/test/java/org/isf/utils/db/TestBCrypt.java, src/test/java/org/isf/utils/file/TestFileTools.java, src/test/java/org/isf/utils/time/TestTimeTools.java
See description in OP-443.
In addition added a test file for some coverage of the class and made minor code updates/improvements.
=> OP-443 fix NPE in utils.FileTools

src/main/java/org/isf/dicom/manager/FileSystemDicomManager.java
Class names start with capital letters (even nested classes).
=> Chore: Classes start with capital letters (even nested classes)

src/main/java/org/isf/patient/manager/PatientBrowserManager.java, src/main/java/org/isf/patient/model/Patient.java, src/test/java/org/isf/patient/TestMergePatient.java, src/test/java/org/isf/patient/test/TestPatient.java
See OP-457.
After this is committed to `develop` the corresponding [PR](https://github.com/informatici/openhospital-gui/pull/427) in the GUI project needs to be committed.
=> OP-457 use camel case names

src/test/java/org/isf/medicalstock/test/Tests.java
What started out as just removing private methods that existed in the base class that differed only by case: `cleanH2InMemoryDB` turned into a file cleanup exercise using SpotBugs, SonarLint, DeadCode, and IntelliJ Analyze.  
There really wasn't any substantive code changes.  The biggest changes are formatting and adding a test for the number of validation messages returned on Exceptions.    No all `assertThatThrownBy` have the test because some methods return a different number of errors based on GeneralData settings and this test is parametrized for various values of `AUTOMATICLOT`.
=> Chore: remove unused private methods

Dockerfile-ohdb
=> OP-456 Update Dockerfile-ohdb to set lower_case_table_name=1

src/main/java/org/isf/examination/manager/ExaminationBrowserManager.java, src/main/java/org/isf/lab/manager/LabManager.java, src/main/java/org/isf/operation/manager/OperationBrowserManager.java, src/main/java/org/isf/patient/manager/PatientBrowserManager.java
See OP-460.
A little formatting was done too.
=> OP-460 fix confusing variable naming

src/main/java/org/isf/dicom/service/DicomIoOperations.java, src/main/java/org/isf/utils/db/DbJpaUtil.java
See OP-462
Took the opportunity to correctly order the import statements in one file too.
=> OP-462 Unnecessary return statement in void method

src/main/java/org/isf/therapy/manager/TherapyManager.java, src/main/java/org/isf/visits/manager/VisitManager.java
=> OP-461 remove redundant string operation

pom.xml
=> OP-354 Fixed Maven dependency

src/main/java/org/isf/accounting/manager/BillBrowserManager.java, src/main/java/org/isf/admission/manager/AdmissionBrowserManager.java, src/main/java/org/isf/dicom/service/DicomIoOperations.java, src/main/java/org/isf/lab/manager/LabManager.java, src/main/java/org/isf/medicalstock/service/MedicalStockIoOperations.java, src/main/java/org/isf/medicalstockward/manager/MovWardBrowserManager.java, src/main/java/org/isf/patient/service/PatientIoOperations.java
=> OP-464 use isEmpty()

sql/load_demo_data.sql
Update demo data to 2021
Update sql file format
Data fixes and corrections
=> Update demo data 2021

src/main/java/org/isf/utils/table/TableSorter.java
Miscellaneous  cleanups, improvements, performance changes including:
- standardized the formatting of the file
- use logging instead of System.println
- remove unnecessary casting
- use primitive types instead of objects were possible
- use faster system array copy method instead of looping
- remove commented out code that wasn't used  (or will be used)
=> Chore: misc cleanup/improvements

src/main/java/org/isf/sms/providers/GSMParameters.java
Remove unused field; found with SpotBugs.
=> Chore: remove unused field

src/main/java/org/isf/dicom/manager/FileSystemDicomManager.java, src/main/java/org/isf/generaldata/ConfigurationProperties.java, src/main/java/org/isf/generaldata/MessageBundle.java, src/main/java/org/isf/serviceprinting/manager/PrintReceipt.java, src/main/java/org/isf/sms/providers/SkebbyGateway.java, src/main/java/org/isf/sms/service/SmsSender.java, src/main/java/org/isf/sms/service/SmsSenderGSM.java, src/main/java/org/isf/sms/service/SmsSenderHTTP.java, src/main/java/org/isf/stat/manager/JasperReportsManager.java, src/main/java/org/isf/utils/db/DbJpaUtil.java, src/main/java/org/isf/utils/db/DbQueryLogger.java, src/main/java/org/isf/utils/db/DbSingleConn.java, src/main/java/org/isf/utils/db/DbSingleJpaConn.java, src/main/java/org/isf/utils/exception/OHException.java, src/main/java/org/isf/utils/exception/OHServiceException.java, src/main/java/org/isf/utils/sms/SetupGSM.java, src/main/java/org/isf/utils/table/TableSorter.java, src/main/java/org/isf/xmpp/manager/Interaction.java, src/main/java/org/isf/xmpp/service/Server.java
=> OP-500 all loggers are private static final

src/main/java/org/isf/generaldata/MessageBundle.java
=> OP-501 add getMnemonic()

src/main/java/org/isf/generaldata/MessageBundle.java
See OP-502 and javadoc in new method
=> OP-502 implement formatMessage() method

src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java, src/main/java/org/isf/medicalstock/model/Lot.java, src/main/java/org/isf/medicalstock/service/LotIoOperationRepository.java, src/main/java/org/isf/medicalstock/service/MedicalStockIoOperations.java, src/main/java/org/isf/medicalstockward/manager/MovWardBrowserManager.java, src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java, src/main/java/org/isf/medstockmovtype/manager/MedicaldsrstockmovTypeBrowserManager.java, src/main/java/org/isf/medstockmovtype/service/MedicalStockMovementTypeIoOperation.java, src/test/java/org/isf/medicals/test/Tests.java, src/test/java/org/isf/medicalstock/test/TestLot.java, src/test/java/org/isf/medicalstock/test/Tests.java, src/test/java/org/isf/medicalstockward/test/Tests.java, src/test/java/org/isf/medstockmovtype/test/Tests.java
=> OP-484 movement and lot fix

src/main/java/org/isf/medicalstockward/manager/MovWardBrowserManager.java, src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java, src/test/java/org/isf/medicalstockward/test/Tests.java
See OP-391 for the rationale.
Note once this is merged then there is a corresponding PR in GUI that is dependent on this change.
=> OP-391 simplify/cleanup newMovementWard()

src/main/java/org/isf/opd/manager/OpdBrowserManager.java
=> OP-470 OH-GUI Fix Error upon insert new patient

src/main/java/org/isf/admission/manager/AdmissionBrowserManager.java
=> OP-514: restore code removed during previous merges

src/main/java/org/isf/admission/manager/AdmissionBrowserManager.java
=> OP-515 Update resource bundle keys for messages in Admission subdirectory

src/main/java/org/isf/dicom/manager/SourceFiles.java, src/main/java/org/isf/dicom/model/FileDicom.java, src/main/java/org/isf/serviceprinting/manager/PrintLabels.java, src/main/java/org/isf/serviceprinting/manager/PrintManager.java, src/main/java/org/isf/serviceprinting/manager/PrintReceipt.java, src/main/java/org/isf/sms/providers/SkebbyGateway.java, src/main/java/org/isf/sms/service/SmsSender.java, src/main/java/org/isf/sms/service/SmsSenderGSM.java, src/main/java/org/isf/utils/db/CSV2SQL.java, src/main/java/org/isf/utils/db/DbJpaUtil.java, src/main/java/org/isf/utils/db/OHServiceExceptionTranslator.java, src/main/java/org/isf/utils/sms/SetupGSM.java, src/main/java/org/isf/utils/time/TimeTools.java, src/main/java/org/isf/xmpp/manager/Interaction.java
=> OP-524 replace printStackTrace() calls

src/main/java/org/isf/ward/manager/WardBrowserManager.java
While looking for unused resource bundle keys found that one key was missing the proper suffix.
The corresponding change to the resource bundle file will be made in a GUI push later today.
=> Chore: add missing resource bundle key suffix

src/main/java/org/isf/admission/manager/AdmissionBrowserManager.java
See OP-553; found while updating the documentation
=> OP-553 fix NPE

sql/load_demo_data.sql
I missed one on the original push
=> OP-557 update keys to match resource bundle

src/main/java/org/isf/admission/service/AdmissionIoOperations.java, src/test/java/org/isf/admission/test/Tests.java
=> OP-569 fix failing maternity tests

pom.xml, src/main/java/org/isf/utils/excel/ExcelExporter.java
as found here https://community.jaspersoft.com/jasperreports-library/issues/13491
we bump to the latest known 100% working version with jasperreports-6.17.0
=> Bump POI from 3.17 to 4.1.2

sql/load_demo_data.sql
=> OP-579 Update shortcut key duplication and missing value

src/main/java/org/isf/accounting/service/AccountingIoOperations.java
=> OP-582 Fix bills comparator when getting bills associated to payments

src/main/java/org/isf/accounting/service/AccountingBillPaymentIoOperationRepository.java, src/test/java/org/isf/accounting/test/Tests.java
=> OP-577 Fix date comparation for payments

src/main/java/org/isf/accounting/model/BillPayments.java, src/test/java/org/isf/accounting/test/Tests.java
=> OP-451 Suspicious 'Comparator.compare()' implementation

src/main/java/org/isf/examination/manager/ExaminationBrowserManager.java, src/main/java/org/isf/examination/service/ExaminationIoOperationRepository.java
=> OP-215 examination module note info

src/main/java/org/isf/patvac/manager/PatVacManager.java, src/main/java/org/isf/patvac/model/PatientVaccine.java, src/test/java/org/isf/patvac/test/Tests.java
See OP-471.
Also changed the whole layout and improved the model
=> OP-471 oh gui vaccine window error

Dockerfile-ohdb, docker-compose.yml
=> OP-540-docker-image-sql-mode

sql/load_demo_data.sql, sql/step_04_all_following_steps.sql, sql/step_69_disclose_accounting_admin_features.sql, src/main/java/org/isf/accounting/service/AccountingBillIoOperationRepository.java, src/main/java/org/isf/accounting/service/AccountingIoOperations.java
=> OP-591 disclose accounting admin features

src/main/java/org/isf/medicalstockward/manager/MovWardBrowserManager.java, src/test/java/org/isf/medicalstockward/test/Tests.java
=> OP-393 remove unused method

src/main/java/org/isf/admission/manager/AdmissionBrowserManager.java, src/main/java/org/isf/admission/service/AdmissionIoOperations.java, src/main/java/org/isf/patient/service/PatientIoOperationRepositoryImpl.java
=> OP-546-inconsistent-search-behavior-in-patient-browser

src/main/java/org/isf/menu/service/MenuIoOperations.java, src/main/java/org/isf/menu/service/UserMenuItemIoOperationRepository.java
=> OP-598-permission-are-saved-but-not-retrieved

src/main/java/org/isf/serviceprinting/manager/PrintLabels.java
See OP-601.
Cc: @claudiorosazza
=> OP-601 Fix label for laboratory sample

src/main/java/org/isf/stat/manager/JasperReportsManager.java
See OP-600.
Cc: @claudiorosazza
=> OP-600 fix ClinicalSheet report

sql/load_demo_data.sql, sql/step_02_dump_menu.sql
=> OP-622 correct shortcut keys

src/main/java/org/isf/sms/providers/textbelt/TextbeltGatewayService.java, src/main/java/org/isf/sms/service/SmsSender.java, src/main/java/org/isf/sms/service/SmsSenderOperations.java
Found with Intellij Analyze plugin
=> Chore: use parameterized logging instead of concatenation

src/main/java/org/isf/stat/manager/JasperReportsManager.java, src/main/java/org/isf/utils/sms/SetupGSM.java
Found with Intellij Analyze plugin
=> Chore: remove unused imports

src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java, src/main/java/org/isf/sms/service/SmsSender.java
Found with Intellij Analyze plugin
=> Chore: remove unnecessary boxing/unboxing

src/main/java/org/isf/generaldata/Version.java
Found with Intellij Analyze plugin
=> Chore: missorted modifiers

src/test/java/org/isf/admission/test/TestAdmission.java
=> Chore: month values are zero based; so 11 not 12

.mvn/wrapper/maven-wrapper.properties
=> OP-629 update maven wrapper version

src/main/java/org/isf/utils/db/Auditable.java
Since this class got overlooked in this PR: https://github.com/informatici/openhospital-core/pull/120
See [OP-331](https://openhospital.atlassian.net/browse/OP-331)
=> OP-331: migrate to java.time Auditable class

Dockerfile-ohdb, sql/create_all_demo.sql, sql/create_all_en.sql, sql/create_all_es.sql, sql/create_all_fr.sql, sql/create_all_it.sql, sql/create_all_pt.sql, sql/step_00_create_user.sql
See OP-344.
Instructions on how to create users are now [here](https://github.com/informatici/openhospital-doc/blob/develop/doc_admin/AdminManual.adoc#3-1-4-open-hospital-database-creation)
=> OP-344 Remove step_00_create_user.sql

src/main/java/org/isf/therapy/manager/TherapyManager.java, src/main/java/org/isf/visits/manager/VisitManager.java, src/main/java/org/isf/visits/model/Visit.java, src/main/java/org/isf/visits/service/VisitsIoOperationRepository.java, src/main/java/org/isf/visits/service/VisitsIoOperations.java, src/test/java/org/isf/visits/test/TestVisit.java, src/test/java/org/isf/visits/test/Tests.java
=> OP-149 Aligned model with relational object and code cleaning/improvement

src/main/java/org/isf/medicalstock/service/MedicalStockIoOperations.java
No need to store result  of method call in a variable so it can then next be tested.
Also did a little re-formatting.
=> Chore: remove unneeded temporary variable

src/main/java/org/isf/accounting/service/AccountingIoOperations.java, src/main/java/org/isf/utils/db/DbSingleJpaConn.java
A little formatting slipped in too
=> Chore: use lambdas available in Java8

src/main/java/org/isf/exa/model/Exam.java, src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java, src/main/java/org/isf/patient/model/Patient.java, src/main/java/org/isf/sms/providers/gsm/GSMGatewayService.java, src/main/java/org/isf/sms/providers/skebby/SkebbyGatewayUtil.java, src/main/java/org/isf/utils/sms/SetupGSM.java
Use Java 5 features:
enhanced for loop
contains()
StringBuilder() instead of StringBuffer()
=> Chore: use Java5 features

src/main/java/org/isf/generaldata/SmsParameters.java
See OP-654
Rebuilt Core and GUI successfully.  All Core unit tests ran OK.
=> OP-654 remove unused/wrong code

src/main/java/org/isf/disease/service/DiseaseIoOperationRepository.java, src/main/java/org/isf/hospital/service/HospitalIoOperations.java, src/main/java/org/isf/lab/manager/LabRowManager.java, src/main/java/org/isf/lab/service/LabRowIoOperationRepository.java, src/main/java/org/isf/medicals/service/MedicalsIoOperationRepository.java, src/main/java/org/isf/menu/service/UserMenuItemIoOperationRepository.java, src/main/java/org/isf/operation/service/OperationRowIoOperationRepository.java, src/main/java/org/isf/pricesothers/service/PriceOthersIoOperations.java, src/main/java/org/isf/serviceprinting/print/MedicalWardForPrint.java, src/main/java/org/isf/visits/service/VisitsIoOperationRepository.java, src/test/java/org/isf/visits/test/TestVisit.java
See OP-468
More files updated since last header update.
=> OP-468 update license headers

src/main/java/org/isf/visits/manager/VisitManager.java, src/main/java/org/isf/visits/model/Visit.java, src/main/java/org/isf/visits/service/VisitsIoOperationRepository.java, src/main/java/org/isf/visits/service/VisitsIoOperations.java, src/test/java/org/isf/visits/test/Tests.java
=> OP-700 Fixing validation error (null ward means ODP)

pom.xml
This PR takes care of updating the dependencies noted in PR-506, PR-510, PR-515, PR-516, PR-517, PR-518, PR-519, and PR-520.
The build was clean and all the tests passed
=> Chore: Update dependencies to latest versions

pom.xml
I will rebase dependabot PRs after this is committed
=> Chore: Update dependencies as found by dependabot

pom.xml
I will rebase the matching PRs once this is committed.
=> Chore: update POM based on dependabot findings

pom.xml
I will rebase the matching PR once this is committed.
=> Chore: Update SpringBoot as found by dependabot

pom.xml
Also changed the jar version from 1.11.99 -> 1.12.0
Will rebase dependabot when this is comitted.
=> Chore: Update feign-gson as found by dependabot

src/main/java/org/isf/visits/manager/VisitManager.java
=> Chore: no need to define type; use <>

src/main/java/org/isf/priceslist/service/PriceListIoOperationRepository.java, src/main/java/org/isf/priceslist/service/PricesListIoOperationRepository.java, src/main/java/org/isf/priceslist/service/PricesListIoOperations.java, src/test/java/org/isf/accounting/test/Tests.java, src/test/java/org/isf/patient/TestMergePatient.java, src/test/java/org/isf/priceslist/test/Tests.java
=> Chore: add missing Override annotation

pom.xml
See OP-734; more testing is needed
=> Chore: revert mysql driver

pom.xml, sql/step_68_update_main_menu.sql, src/main/java/org/isf/utils/db/DbSingleConn.java, src/test/resources/version.properties
=> Merge Hotfix v1.11.1

src/main/java/org/isf/patient/manager/PatientBrowserManager.java
=> OP-743 make method name match the pattern

pom.xml, src/main/java/org/isf/admission/service/AdmissionIoOperations.java
See OP-332
JapserReports was defined both in CORE and GUI although only the fonts dependency was in GUI.  Moved them all together in this project and will remove from GUI pom.xml.
=> OP-332 replace iText with librepdf

pom.xml
Per dependabot; will rebase after this is committed.
=> Chore: update maven-jar-plugin to 3.2.1

pom.xml
I will rebase when this is committed to develop.
=> Chore: plugin updates per dependabot

src/main/java/org/isf/dicomtype/manager/DicomTypeBrowserManager.java, src/main/java/org/isf/examination/manager/ExaminationBrowserManager.java, src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java, src/main/java/org/isf/opetype/manager/OperationTypeBrowserManager.java, src/main/java/org/isf/patient/manager/PatientBrowserManager.java
See OP-744
Made changes noted in points 1, 2, and 3 in the issue description.
=> OP-744 standardize validation routine contract

src/main/resources/applicationContext.xml
See OP-746.
Removes warning message from GUI startup log.
=> OP-746 Update default mysql driver to latest version

src/main/java/org/isf/patient/manager/PatientBrowserManager.java, src/test/java/org/isf/patient/TestMergePatient.java
See OP-747
Simplify code and update tests for one less message.
=> OP-747 remove extra message(s)

pom.xml
Made dependency updates as outlined in the release notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.6.3
=> Chore: Update to SpringBoot 2.6.3

pom.xml
Combined all dependabot jar updates (except for H2) into one so all the unit tests in Core and Gui could be run and verified together incase there was some interaction.  Also did some interactive GUI testing after installing the jar.
=> Chore: update all outstanding dependabot jars

pom.xml
Will rebase the other PRs when this is committed.
=> Chore: combine all recent dependabot updates into one PR to test all of them together

sql/extra/extra_XX_adjust_opd_datetime.sql, src/main/java/org/isf/opd/manager/OpdBrowserManager.java, src/main/java/org/isf/opd/model/Opd.java, src/main/java/org/isf/opd/service/OpdIoOperationRepository.java, src/main/java/org/isf/opd/service/OpdIoOperationRepositoryImpl.java, src/main/java/org/isf/opd/service/OpdIoOperations.java, src/test/java/org/isf/opd/test/TestOpd.java, src/test/java/org/isf/opd/test/Tests.java
See OP-760.
Paired with https://github.com/informatici/openhospital-gui/pull/1118.
Will follow OP-761 after v1.11.3
=> OP-760 OPD visits honoring date AND time now

sql/extra/extra_XX_adjust_lab_datetime.sql, src/main/java/org/isf/lab/manager/LabManager.java, src/main/java/org/isf/lab/model/Laboratory.java, src/main/java/org/isf/lab/service/LabIoOperationRepository.java, src/main/java/org/isf/lab/service/LabIoOperations.java, src/main/java/org/isf/opd/model/Opd.java, src/test/java/org/isf/lab/test/TestLaboratory.java, src/test/java/org/isf/lab/test/Tests.java
See OP-774.
Paired with https://github.com/informatici/openhospital-gui/pull/1138.
Will follow OP-781 after v1.11.3
=> Op 774 laboratory honoring date and time now

src/main/java/org/isf/patvac/service/PatVacIoOperationRepositoryImpl.java
See OP-818
Uses the hotfix branch as its base.
=> OP-818 fix subsetting by vaccine type value

pom.xml
This ensures that when all are updated the tests still pass.
When merged I will close the dependabot PRs.
=> Chore: combine all recent non-held dependabot updates

pom.xml
I will rebase the individual buildbot PRs after this is merged.
=> Chore combine all recent dependabot updates to test as a single unit

sql/load_demo_data.sql, sql/step_04_all_following_steps.sql, sql/step_74_operation_report_button.sql, src/main/java/org/isf/stat/manager/JasperReportsManager.java
See OP-910.
Add a method to the JasperReportsManager to get the operations list;
update the sql file to insert the button Operations into the menu
=> OP-910 - Add print button for Operations in Main Menu \ Reports

pom.xml
Combine the suggested dependabot updates for the last three weeks and test them as a single unit.
Ran "mvn clean test" without errors.
Once this is merged I will rebase the dependabot PRs.
=> Chore: combine all recent dependabot updates

src/main/java/org/isf/serviceprinting/print/MovementForPrint.java, src/main/java/org/isf/serviceprinting/print/MovementWardForPrint.java
=> OP-928 convert to Date for reporting

src/main/java/org/isf/utils/db/DbQueryLogger.java
=> OP-945 allow ResultSet to be accessed by not auto closing the connection

pom.xml
Combine all recent dependabot jar updates to test together.
Will rebase the other commits once this is merged.
=> Chore: combine all recent dependabot jar updates to test together

src/main/java/org/isf/medicalstock/service/MovementIoOperationRepositoryImpl.java
=> OP-946 Fix IllegalArgumentException in Pharmaceutical Stock

src/main/java/org/isf/utils/excel/ExcelExporter.java
See OP-947   
This is the hotfix version
=> OP-947 do not export the button object to Excel file

src/main/java/org/isf/visits/manager/VisitManager.java, src/test/java/org/isf/ward/test/TestWard.java, src/test/java/org/isf/ward/test/Tests.java
This is the hotfix version
See OP-939
=> OP-939 add additional validation logic for visit

src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java
=> OP-948 fix count of medical stock when moving to another ward

pom.xml
Will rebase dependabot PRs when this is committed.
Tested with `mvn clean install`
=> Chore: combine all recent dependabot jar updates

pom.xml
Combined all 5 together and successfully ran `mvn clean test`
When this is committed I will rebase the individual PRs
=> Chore: combine the 5 most recent dependabot updates into single PR for testing

pom.xml
Tests clean in IDE and running `mvn clean test`
I will rebase the dependabot PRs when this is merged.
=> Chore: combine 7 recent dependabot updates into single PR for testing

pom.xml
Around round of updates tested together.   All tests clean in IDE and `mvn clean test`.
=> Chore: combine 6 recent dependabot updates into single PR for testing

sql/extra/extra_XX_dicom_button_in_admission_patient.sql, sql/load_demo_data.sql, sql/step_04_all_following_steps.sql, sql/step_76_dicom_button_in_admission_patient.sql
See OP-844
Note: the button name will change to Image when OP-846 is done.
=> OP-844 add DICOM button in Admission/Patient Browser

sql/extra/extra_XX_laboratory_button_in_admission_patient.sql, sql/load_demo_data.sql, sql/step_04_all_following_steps.sql, sql/step_77_laboratory_button_in_admission_patient.sql
=> OP-845 Add Laboratory button in Admission/Patient

src/main/java/org/isf/dicom/manager/SourceFiles.java
=> OP-969 Remove JPEGImageReader

src/main/java/org/isf/menu/service/MenuIoOperations.java, src/main/java/org/isf/menu/service/UserIoOperationRepository.java
See OP-977
Changes required to persist changes to both user description and group
=> OP-977 changes to persist usergroup changes

src/main/java/org/isf/lab/manager/LabManager.java, src/test/java/org/isf/lab/test/Tests.java
=> OP-985 remove results check for lab type 2; no labrows for negative results

sql/load_demo_data.sql, sql/step_81_link_bill_admission.sql, src/main/java/org/isf/accounting/model/Bill.java
See OP-875.
Paired with https://github.com/informatici/openhospital-gui/pull/1342.
=> OP-875 link bill admission - core

src/main/java/org/isf/accounting/model/Bill.java
=> OP-990 remove CascadeType.Merge to stop unnecessary ObjectOptimisticLockingFailureException

.github/workflows/maven.yml, pom.xml
=> OP-854 Move to JDK 11 - core

pom.xml
Will rebase other PRs after merge.
=> Chore: combine recent dependabot updates into single PR for testing

src/main/java/org/isf/patient/model/Patient.java
=> Restore FetchType.LAZY on PatientProfilePhoto

src/main/java/org/isf/patient/service/PatientIoOperations.java
=> OP-987 - OP-138 causes getPatientId to update at each read

pom.xml
=> Hotfix for 1.11.4

src/main/java/org/isf/patient/service/PatientIoOperations.java
=> OP-1003 - db profile picture persists upon patient deletion

src/main/java/org/isf/dicom/manager/FileSystemDicomManager.java, src/main/java/org/isf/dicom/manager/SourceFiles.java
See OP-981.
Also fixed folder loading interruption when one or more file are not supported, instead it logs the error and continues the loading.
=> OP-981 dicom series for jpegs

src/main/java/org/isf/lab/model/Laboratory.java
=> OP-1023 Add getLabDate() so reflection code works

src/main/java/org/isf/lab/manager/LabManager.java, src/main/java/org/isf/lab/service/LabIoOperations.java
=> staging3test addendum

src/main/java/org/isf/admission/model/Admission.java, src/main/java/org/isf/admission/service/AdmissionIoOperations.java, src/main/java/org/isf/patient/model/Patient.java, src/main/java/org/isf/patient/service/PatientIoOperationRepository.java, src/main/java/org/isf/patient/service/PatientIoOperationRepositoryImpl.java, src/main/java/org/isf/patient/service/PatientIoOperations.java, src/main/java/org/isf/supplier/model/Supplier.java, src/main/java/org/isf/utils/db/TranslateOHServiceException.java, src/test/java/org/isf/admission/test/TestAdmission.java, src/test/java/org/isf/patient/TestMergePatient.java, src/test/java/org/isf/patient/test/Tests.java, src/test/java/org/isf/ward/test/Tests.java
=> OP-527 inconsistent column definition for XXX_DELETED fields

src/main/java/org/isf/opd/manager/OpdBrowserManager.java, src/main/java/org/isf/opd/service/OpdIoOperationRepositoryCustom.java, src/main/java/org/isf/opd/service/OpdIoOperationRepositoryImpl.java, src/main/java/org/isf/opd/service/OpdIoOperations.java, src/test/java/org/isf/opd/test/Tests.java
See OP-213.
Add also USER column and related filter (like in Wolisso's project).
=> OP-213 add search field for opd records

src/main/java/org/isf/lab/manager/LabManager.java, src/main/java/org/isf/lab/service/LabIoOperations.java
…ratoryForPrintUsingGET in order to return a list of LabWithRowsDTO
=> Update staging3Test for informatici

src/main/java/org/isf/medicalstock/service/MovementIoOperationRepositoryImpl.java, src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperationRepositoryImpl.java
=> OP-1047 fix the filtering by dates using the between predicate

src/main/java/org/isf/stat/manager/JasperReportsManager.java
=> OP-1049 Fix error from OP-999

sql/load_demo_data.sql
Updated demo data with latest sql updates.
=> OP-897 Update Demo Data

src/main/java/org/isf/dicom/manager/FileSystemDicomManager.java, src/main/java/org/isf/stat/manager/JasperReportsManager.java, src/main/java/org/isf/therapy/model/Therapy.java
=> OP-1052: Use String.valueOf() instead of empty string concatenation

pom.xml
Update maven-surefire-plugin to match version in GUI: https://github.com/informatici/openhospital-gui/pull/1720
Ran tests in IDE and `mvn clean test` without issue.
=> Chore: update maven-surefire-plugin

pom.xml
Release Notes; https://github.com/spring-projects/spring-boot/releases/tag/v2.7.10
=> Chore: upgrade to Spring Boot 2.7.10

src/main/java/org/isf/utils/exception/model/OHExceptionMessage.java, src/main/java/org/isf/visits/manager/VisitManager.java, src/main/java/org/isf/visits/model/Visit.java, src/test/java/org/isf/visits/test/Tests.java
See OP-722.
- avoid overlapping visits within the same ward
- avoid patients ubiquity, i.e. overlapping same patient visit in different wards
- also check the visit duration is > 0
=> OP-722 Validate that a visit does not overlap other visits

src/main/java/org/isf/accounting/manager/BillBrowserManager.java, src/main/java/org/isf/admission/manager/AdmissionBrowserManager.java, src/main/java/org/isf/admtype/manager/AdmissionTypeBrowserManager.java, src/main/java/org/isf/agetype/manager/AgeTypeBrowserManager.java
See OP-1066
Core packages that start with 'A`
=> OP-1066 new OHExceptionMessage() constructor; packages that start with A

src/main/java/org/isf/dicom/manager/DicomManagerFactory.java, src/main/java/org/isf/dicom/manager/FileSystemDicomManager.java, src/main/java/org/isf/dicom/manager/SourceFiles.java, src/main/java/org/isf/dicomtype/manager/DicomTypeBrowserManager.java, src/main/java/org/isf/disctype/manager/DischargeTypeBrowserManager.java, src/main/java/org/isf/disease/manager/DiseaseBrowserManager.java, src/main/java/org/isf/distype/manager/DiseaseTypeBrowserManager.java, src/main/java/org/isf/dlvrrestype/manager/DeliveryResultTypeBrowserManager.java, src/main/java/org/isf/dlvrtype/manager/DeliveryTypeBrowserManager.java
Core packages that start with 'D`
=> OP-1066 new OHExceptionMessage() constructor; packages that start with D

src/main/java/org/isf/exa/manager/ExamBrowsingManager.java, src/main/java/org/isf/exa/manager/ExamRowBrowsingManager.java, src/main/java/org/isf/examination/manager/ExaminationBrowserManager.java, src/main/java/org/isf/exatype/manager/ExamTypeBrowserManager.java, src/main/java/org/isf/lab/manager/LabManager.java
Core packages that start with 'E' and 'L`
=> OP-1066 new OHExceptionMessage() constructor; packages that start with E and L

src/main/java/org/isf/opd/manager/OpdBrowserManager.java, src/main/java/org/isf/opetype/manager/OperationTypeBrowserManager.java, src/main/java/org/isf/patient/manager/PatientBrowserManager.java, src/main/java/org/isf/patient/service/FileSystemPatientPhotoRepository.java, src/main/java/org/isf/patvac/manager/PatVacManager.java, src/main/java/org/isf/pregtreattype/manager/PregnantTreatmentTypeBrowserManager.java, src/main/java/org/isf/priceslist/manager/PriceListManager.java, src/main/java/org/isf/pricesothers/manager/PricesOthersManager.java
Core packages that start with 'O' and 'P'
=> OP-1066 new OHExceptionMessage() constructor; packages that start with O and P

src/main/java/org/isf/malnutrition/manager/MalnutritionManager.java, src/main/java/org/isf/medicals/manager/MedicalBrowsingManager.java, src/main/java/org/isf/medicalstock/manager/MovBrowserManager.java, src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java, src/main/java/org/isf/medicalstockward/manager/MovWardBrowserManager.java, src/main/java/org/isf/medstockmovtype/manager/MedicaldsrstockmovTypeBrowserManager.java, src/main/java/org/isf/medtype/manager/MedicalTypeBrowserManager.java, src/main/java/org/isf/menu/manager/UserBrowsingManager.java
Core packages that start with 'M'
=> OP-1066 new OHExceptionMessage() constructor; packages that start with M

src/main/java/org/isf/sms/manager/SmsManager.java, src/main/java/org/isf/stat/manager/JasperReportsManager.java, src/main/java/org/isf/utils/db/OHServiceExceptionTranslator.java
Core packages that start with 'S' and 'U'
=> OP-1066 new OHExceptionMessage() constructor; packages that start with S and U

src/main/java/org/isf/vaccine/manager/VaccineBrowserManager.java, src/main/java/org/isf/vactype/manager/VaccineTypeBrowserManager.java, src/main/java/org/isf/ward/manager/WardBrowserManager.java
Core packages that start with 'V' and 'W'
=> OP-1066 new OHExceptionMessage() constructor; packages that start with V and W

pom.xml
Combine 3 valid dependabot updates into single PR.
`mvn clean test` was sucessful.
I will rebase the original PRs after this is merged.
=> Chore: combine dependabot updates into single PR for testing

src/main/java/org/isf/generaldata/GeneralData.java
=> OP-894 use value of zero to turn off password length checking

src/main/java/org/isf/lab/manager/LabManager.java, src/main/java/org/isf/lab/service/LabIoOperationRepository.java, src/main/java/org/isf/lab/service/LabIoOperations.java
=> OP-1064 Make list of exams laboratory parametric and pageable

src/main/java/org/isf/admission/model/Admission.java, src/main/java/org/isf/dicomtype/service/DicomTypeIoOperation.java, src/main/java/org/isf/lab/manager/LabManager.java, src/main/java/org/isf/medicals/manager/MedicalBrowsingManager.java, src/main/java/org/isf/patient/model/Patient.java, src/main/java/org/isf/patient/service/PatientIoOperations.java, src/main/java/org/isf/sessionaudit/manager/SessionAuditManager.java, src/main/java/org/isf/sessionaudit/service/SessionAuditIoOperation.java, src/main/java/org/isf/sms/service/SmsOperations.java, src/main/java/org/isf/stat/manager/JasperReportsManager.java, src/main/java/org/isf/utils/excel/ExcelExporter.java, src/main/java/org/isf/utils/time/TimeTools.java
Found with Intellij Analyze and DocLint
=> Chore: JavaDoc improvements

src/main/java/org/isf/examination/model/PatientExamination.java
See OP-1073
All tests ran cleanly.
=> OP-1073 Extend from Auditable class like other objects

src/main/java/org/isf/generaldata/GeneralData.java
=> OP-1076 set default password length to 6

src/main/java/org/isf/exa/manager/ExamBrowsingManager.java, src/test/java/org/isf/exa/test/Tests.java
See OP-1082
Rebuilt the Core jar and rebuild GUI and API repos cleanly.
=> OP-1082: Remove deprecated methods org.isf.exa.manager.ExamBrowsingManager

src/main/java/org/isf/lab/manager/LabManager.java, src/main/java/org/isf/lab/model/Laboratory.java, src/main/java/org/isf/lab/service/LabIoOperations.java, src/test/java/org/isf/lab/test/TestLaboratory.java, src/test/java/org/isf/lab/test/Tests.java
See OP-1086
Rebuilt the jar and ran all the tests successfully.
=> OP-1086: remove deprecated methods from org.isf.lab.model.Laboratory

src/main/java/org/isf/utils/excel/ExcelExporter.java
See OP-1081
Rebuilt core jar and then rebuild GUI and API repos cleanly.
=> OP-1081: Remove @deprecated annotation in org.isf.utils.excel.ExcelExporter

src/main/java/org/isf/lab/manager/LabManager.java, src/test/java/org/isf/lab/test/Tests.java
See OP-1089
Removed methods, rebuilt the jar, ran the unit tests.
Used new jar to rebuild GUI and API without errors.   Ran all the API tests successfully.
=> OP-1089 Remove deprecated methods from org.isf.lab.manager.LabManager

pom.xml
=> OP-1094 Update JasperReport library to 6.20.5

pom.xml
Ran `mvn clean test` without error.
I will force a rebase on the individual PRs after this is merged.
=> Chore: combine recent dependabot updates together for testing

src/main/java/org/isf/menu/manager/UserBrowsingManager.java
=> OP-1072: add method that unlocks a user account

sql/update/README.md, sql/update/update_1_10-1_11.sql, sql/update/update_1_11-1_12.sql, sql/update/update_1_12-1_13.sql, sql/update/update_1_8_4-1_9.sql, sql/update/update_1_9-1_10.sql
Update sql update scripts for 1.13.
=> 1.13 release update

src/main/java/org/isf/operation/service/OperationIoOperationRepository.java
This was part of today's earlier commit.
=> Chore: remove unused import

src/main/java/org/isf/opd/manager/OpdBrowserManager.java, src/main/java/org/isf/opd/service/OpdIoOperationRepository.java, src/main/java/org/isf/opd/service/OpdIoOperations.java, src/test/java/org/isf/opd/test/TestOpd.java
=> OH2-226: Add param wardCode on api opd search

pom.xml, src/main/java/org/isf/generaldata/ConfigurationProperties.java
`mvn clean test` and`mvn clean install` run cleanly and interactive GUI testing looks good.
=> Chore: combine recent dependabot jar updates for testing

src/main/java/org/isf/lab/model/LaboratoryForPrint.java, src/main/java/org/isf/lab/service/LabIoOperations.java, src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java, src/main/java/org/isf/patient/service/FileSystemPatientPhotoRepository.java, src/main/java/org/isf/patvac/service/PatVacIoOperations.java, src/main/java/org/isf/permissions/service/PermissionIoOperations.java
Rebuilt the jar with these changes and then rebuild and tested GUI and API.
=> Chore: remove unused fields, variables, methods

src/main/java/org/isf/admission/service/AdmissionIoOperationRepositoryImpl.java, src/main/java/org/isf/dicom/manager/FileSystemDicomManager.java, src/main/java/org/isf/operation/model/OperationRow.java, src/main/java/org/isf/operation/service/OperationIoOperations.java, src/main/java/org/isf/patconsensus/model/PatientConsensus.java, src/main/java/org/isf/patient/service/PatientIoOperationRepositoryImpl.java, src/main/java/org/isf/serviceprinting/manager/PrintManager.java, src/main/java/org/isf/serviceprinting/manager/PrintReceipt.java, src/main/java/org/isf/sms/model/Sms.java, src/main/java/org/isf/sms/providers/skebby/SkebbyGatewayService.java, src/main/java/org/isf/sms/providers/skebby/model/SckebbySmsRequest.java, src/main/java/org/isf/sms/providers/textbelt/model/TextbeltSmsRequest.java, src/main/java/org/isf/sms/providers/textbelt/model/TextbeltSmsResponse.java, src/main/java/org/isf/stat/manager/JasperReportsManager.java, src/main/java/org/isf/therapy/model/TherapyRow.java, src/main/java/org/isf/utils/excel/ExcelExporter.java, src/main/java/org/isf/utils/sms/SetupGSM.java, src/main/java/org/isf/vaccine/model/Vaccine.java, src/main/java/org/isf/vactype/model/VaccineType.java, src/main/java/org/isf/ward/model/Ward.java
=> Chore: use 'char' instead of single character 'String'

src/main/java/org/isf/lab/model/LaboratoryForPrint.java, src/main/java/org/isf/sms/providers/gsm/GSMGatewayService.java, src/main/java/org/isf/utils/sms/SetupGSM.java, src/test/java/org/isf/medicalstockward/test/Tests.java, src/test/java/org/isf/patient/TestMergePatient.java, src/test/java/org/isf/priceslist/test/TestPrice.java
Improve class size and readability of code
=> Chore: class fields moved to being local variables

pom.xml
Release Notes: https://github.com/spring-projects/spring-framework/releases/tag/v5.3.30
=> Upgrade to Spring Framework 5.3.30

pom.xml
Release notes; https://github.com/spring-projects/spring-boot/releases/tag/v2.7.16
`mvn clean test` ran cleanly
=> Upgrade to Spring Boot 2.7.16

src/main/java/org/isf/accounting/manager/BillBrowserManager.java, src/main/java/org/isf/accounting/service/AccountingBillIoOperationRepository.java, src/main/java/org/isf/accounting/service/AccountingIoOperations.java, src/test/java/org/isf/accounting/test/Tests.java
See OP-1130
Changes for the accounting package in Core; no corresponding changes required for GUI but there are 3 required in API (which I will create a PR for if these changes are accepted).
=> OP-1130 improve JPA methods

src/main/java/org/isf/anamnesis/manager/PatientHistoryManager.java, src/main/java/org/isf/anamnesis/service/PatientHistoryIoOperations.java
See OP-1130
Changes for anamnesis package
No changes needed in GUI or API
=> OP-1130 improve JPA methods - anamnesis package

src/main/java/org/isf/admission/manager/AdmissionBrowserManager.java, src/main/java/org/isf/admission/service/AdmissionIoOperationRepositoryCustom.java, src/main/java/org/isf/admission/service/AdmissionIoOperationRepositoryImpl.java, src/main/java/org/isf/admission/service/AdmissionIoOperations.java, src/test/java/org/isf/admission/test/Tests.java
See OP-1130
Changes for the admission package in Core; requires corresponding changes and the GUI and  API repo for which I will create the two PRs.
=> OP-1130 improve JPA methods - admission package

src/main/java/org/isf/admtype/manager/AdmissionTypeBrowserManager.java, src/main/java/org/isf/admtype/model/AdmissionType.java, src/main/java/org/isf/admtype/service/AdmissionTypeIoOperation.java, src/test/java/org/isf/admtype/test/Tests.java
See OP-1130
Changes for the admtype package in Core; requires corresponding changes int the GUI and the API repo for which I will create the two PRs.
=> OP-1130 improve JPA methods - admtype package

src/main/java/org/isf/agetype/manager/AgeTypeBrowserManager.java, src/main/java/org/isf/agetype/service/AgeTypeIoOperations.java, src/test/java/org/isf/agetype/test/Tests.java
See [OP-1130](https://openhospital.atlassian.net/browse/OP-1130)
Changes for the agetype package in Core; requires corresponding changes in the API repo for which I will create the PR.
[OP-1130]: https://openhospital.atlassian.net/browse/OP-1130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1130 improve JPA methods - agetype package

src/main/java/org/isf/dicomtype/manager/DicomTypeBrowserManager.java, src/main/java/org/isf/dicomtype/service/DicomTypeIoOperation.java, src/test/java/org/isf/dicomtype/test/Tests.java
See OP-1130
Changes to dicomtype package
There are corresponding changes in GUI and no changes in API
=> OP-1130 improve JPA methods - dicomtype package

src/main/java/org/isf/opd/manager/OpdBrowserManager.java, src/main/java/org/isf/opd/service/OpdIoOperationRepository.java, src/main/java/org/isf/opd/service/OpdIoOperations.java
=> OH2-239 | 500 error when paged is true on api opd search

src/main/java/org/isf/distype/manager/DiseaseTypeBrowserManager.java, src/main/java/org/isf/distype/service/DiseaseTypeIoOperation.java, src/test/java/org/isf/distype/test/Tests.java
See OP-1130
Changes for distype package.
=> OP-1130 improve JPA methods - distype package

src/main/java/org/isf/dlvrrestype/manager/DeliveryResultTypeBrowserManager.java, src/main/java/org/isf/dlvrrestype/service/DeliveryResultTypeIoOperation.java, src/test/java/org/isf/dlvrrestype/test/Tests.java
See OP-1130
Changes for dlvrrestype package
=> OP-1130 improve JPA methods - dlvrrestype package

src/main/java/org/isf/dlvrtype/manager/DeliveryTypeBrowserManager.java, src/main/java/org/isf/dlvrtype/model/DeliveryType.java, src/main/java/org/isf/dlvrtype/service/DeliveryTypeIoOperation.java, src/test/java/org/isf/dlvrtype/test/Tests.java
See OP-1130
Changes for dlvrtype package
=> OP-1130 improve JPA methods - dlvrtype package

src/main/java/org/isf/exatype/manager/ExamTypeBrowserManager.java, src/main/java/org/isf/exatype/model/ExamType.java, src/main/java/org/isf/exatype/service/ExamTypeIoOperation.java, src/test/java/org/isf/exatype/test/Tests.java
See OP-1130
Changes for exatype package
=> OP-1130 improve JPA methods - exatype package

src/main/java/org/isf/exa/manager/ExamBrowsingManager.java, src/main/java/org/isf/exa/manager/ExamRowBrowsingManager.java, src/main/java/org/isf/exa/service/ExamIoOperations.java, src/main/java/org/isf/exa/service/ExamRowIoOperations.java, src/test/java/org/isf/exa/test/Tests.java
See OP-1130
Changes for exa package
=> OP-1130 improve JPA methods - exa package

src/main/java/org/isf/disease/manager/DiseaseBrowserManager.java, src/main/java/org/isf/disease/service/DiseaseIoOperations.java, src/test/java/org/isf/disease/test/Tests.java
See OP-1130
Changes for the disease package
=> OP-1130 improve JPA methods - disease package

src/main/java/org/isf/examination/manager/ExaminationBrowserManager.java, src/main/java/org/isf/examination/service/ExaminationOperations.java
See OP-1130
Changes for examination package
=> OP-1130 improve JPA methods - examination package

src/main/java/org/isf/hospital/manager/HospitalBrowsingManager.java, src/main/java/org/isf/hospital/service/HospitalIoOperations.java, src/test/java/org/isf/hospital/test/Tests.java
See OP-1130
Changes for hospital package.
Note there are no real code changes (except for the tests when the optional return of an object is checked for) but rather javadoc updates.
In addition there are no changes required for this package in the GUI and/or API repos.
=> OP-1130 improve JPA methods - hospital package

src/main/java/org/isf/medicals/manager/MedicalBrowsingManager.java, src/main/java/org/isf/medicals/service/MedicalsIoOperations.java, src/test/java/org/isf/medicals/test/Tests.java
See OP-1130
Changes for the medicals package
=> OP-1130 improve JPA methods - medicals package

src/main/java/org/isf/medtype/manager/MedicalTypeBrowserManager.java, src/main/java/org/isf/medtype/service/MedicalTypeIoOperation.java, src/test/java/org/isf/medtype/test/Tests.java
See OP-1130
Changes for the `medtype` package
=> OP-1130 improve JPA methods - medtype package

src/main/java/org/isf/opd/manager/OpdBrowserManager.java, src/main/java/org/isf/opd/service/OpdIoOperations.java, src/test/java/org/isf/opd/test/Tests.java
See OP-1130
Changes for the `opd` package
=> OP-1130 improve JPA methods - opd package

src/main/java/org/isf/opetype/manager/OperationTypeBrowserManager.java, src/main/java/org/isf/opetype/service/OperationTypeIoOperation.java, src/test/java/org/isf/opetype/test/Tests.java
See OP-1130.
Changes for the `opetype` package.
=> OP-1130 improve JPA methods - opetype package

src/main/java/org/isf/pregtreattype/manager/PregnantTreatmentTypeBrowserManager.java, src/main/java/org/isf/pregtreattype/service/PregnantTreatmentTypeIoOperation.java, src/test/java/org/isf/pregtreattype/test/Tests.java
See OP-1130
Changes for 'pregtreattype` package
=> OP-1130 improve JPA methods - pregtreattype package

src/main/java/org/isf/vactype/manager/VaccineTypeBrowserManager.java, src/main/java/org/isf/vactype/service/VacTypeIoOperation.java, src/test/java/org/isf/vactype/test/Tests.java
See OP-1130
Changes for `vactype` package
=> OP-1130 improve JPA methods - vactype package

src/main/java/org/isf/vaccine/manager/VaccineBrowserManager.java, src/main/java/org/isf/vaccine/service/VaccineIoOperations.java, src/test/java/org/isf/vaccine/test/Tests.java
See OP-1130
Changes for the `vaccine` package
=> OP-1130 improve JPA methods - vaccine package

src/main/java/org/isf/ward/manager/WardBrowserManager.java, src/main/java/org/isf/ward/service/WardIoOperations.java, src/test/java/org/isf/ward/test/Tests.java
See OP-1130
Changes for the `ward` package
=> OP-1130 improve JPA methods - ward package

src/main/java/org/isf/visits/service/VisitsIoOperations.java
See OP-1130
Changes for the `visits` package.
No real code changes just javadoc to watch changes in the other packages undergoing updates.
=> OP-1130 improve JPA methods - visits package

src/main/java/org/isf/therapy/manager/TherapyManager.java, src/main/java/org/isf/therapy/service/TherapyIoOperations.java, src/test/java/org/isf/therapy/test/Tests.java
See OP-1130
Changes for the `therapy` package
=> OP-1130 improve JPA methods - therapy package

src/main/java/org/isf/supplier/manager/SupplierBrowserManager.java, src/main/java/org/isf/supplier/service/SupplierOperations.java, src/test/java/org/isf/supplier/test/Tests.java
See OP-1130
Changes for the `supplier` package
=> OP-1130 improve JPA methods - supplier package

src/main/java/org/isf/pricesothers/manager/PricesOthersManager.java, src/main/java/org/isf/pricesothers/service/PriceOthersIoOperations.java, src/test/java/org/isf/pricesothers/test/Tests.java
See OP-1130
Changes for `pricesothers` package
=> OP-1130 improve JPA methods - pricesothers package

src/main/java/org/isf/sessionaudit/manager/SessionAuditManager.java, src/main/java/org/isf/sessionaudit/service/SessionAuditIoOperation.java
See OP-1130
Changes for `sessionaudit` package
There are no corresponding changes for GUI and API packages.
=> OP-1130 improve JPA methods - sessionaudit package

src/main/java/org/isf/patvac/manager/PatVacManager.java, src/main/java/org/isf/patvac/service/PatVacIoOperations.java, src/test/java/org/isf/patvac/test/Tests.java
See OP-1130
Changes for `patvac` package
=> OP-1130 improve JPA methods - patvac package

src/main/java/org/isf/patconsensus/manager/PatientConsensusBrowserManager.java, src/main/java/org/isf/patconsensus/service/PatientConsensusIoOperation.java
See OP-1130
Changes for package `patconsensus`
=> OP-1130 improve JPA methods - patconsensus package

src/main/java/org/isf/patient/manager/PatientBrowserManager.java, src/main/java/org/isf/patient/service/FileSystemPatientPhotoRepository.java, src/main/java/org/isf/patient/service/PatientIoOperationRepositoryImpl.java, src/main/java/org/isf/patient/service/PatientIoOperations.java, src/test/java/org/isf/patient/TestMergePatient.java, src/test/java/org/isf/patient/test/Tests.java
See OP-1130
Changes for the `patient` package
=> OP-1130 improve JPA methods - patient package

src/main/java/org/isf/operation/manager/OperationRowBrowserManager.java, src/main/java/org/isf/operation/service/OperationRowIoOperations.java, src/test/java/org/isf/operation/test/Tests.java
See OP-1130
Changes for the `operation` package.
Note: this requires an additional message in the bundle file in the GUI repo.
=> OP-1130 improve JPA methods - operation package

src/main/java/org/isf/priceslist/manager/PriceListManager.java, src/main/java/org/isf/priceslist/service/PricesListIoOperations.java, src/test/java/org/isf/priceslist/test/Tests.java
See OP-1130
Changes for `priceslist` package
=> OP-1130 improve JPA methods - priceslist package

src/main/java/org/isf/permissions/manager/GroupPermissionManager.java, src/main/java/org/isf/permissions/manager/PermissionManager.java, src/main/java/org/isf/permissions/service/GroupPermissionIoOperations.java, src/main/java/org/isf/permissions/service/PermissionIoOperations.java
See OP-1130
Changes for the `permissions` package
Note: not changes required in GUI but many changes required here for adding the `throws` clause that was missing.
=> OP-1130 improve JPA methods - permissions package

src/main/java/org/isf/menu/manager/UserBrowsingManager.java, src/main/java/org/isf/menu/service/MenuIoOperations.java, src/test/java/org/isf/menu/test/Tests.java
See OP-1130
Changes for `menu` package
=> OP-1130 improve JPA methods - menu package

src/main/java/org/isf/medstockmovtype/manager/MedicalDsrStockMovementTypeBrowserManager.java, src/main/java/org/isf/medstockmovtype/service/MedicalDsrStockMovementTypeIoOperation.java, src/test/java/org/isf/medstockmovtype/test/Tests.java
See OP-1130
Changes for `medstockmovtype` package
=> OP-1130 improve JPA methods - medstockmovtype package

src/main/java/org/isf/medicalstockward/manager/MovWardBrowserManager.java, src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java, src/test/java/org/isf/medicalstockward/test/Tests.java
See OP-1130
Changes for `medicalstockward` package
Note there are no corresponding changes for the API repo.
=> OP-1130 improve JPA methods - medicalstockward package

src/main/java/org/isf/stat/manager/JasperReportsManager.java
=> OP-1159 Fix patient profile picture in reports when loaded from FS

src/main/java/org/isf/accounting/model/Bill.java, src/main/java/org/isf/accounting/model/BillItems.java, src/main/java/org/isf/accounting/model/BillPayments.java, src/main/java/org/isf/admission/model/Admission.java, src/main/java/org/isf/admission/service/AdmissionIoOperations.java, src/main/java/org/isf/admtype/model/AdmissionType.java, src/main/java/org/isf/agetype/model/AgeType.java, src/main/java/org/isf/dicom/model/FileDicom.java, src/main/java/org/isf/dicom/service/DicomIoOperations.java, src/main/java/org/isf/disctype/model/DischargeType.java, src/main/java/org/isf/disease/manager/DiseaseBrowserManager.java, src/main/java/org/isf/disease/model/Disease.java, src/main/java/org/isf/disease/service/DiseaseIoOperations.java, src/main/java/org/isf/distype/model/DiseaseType.java, src/main/java/org/isf/dlvrrestype/model/DeliveryResultType.java, src/main/java/org/isf/dlvrtype/model/DeliveryType.java
See OP-1075
Packages a to d (about 1/4 of all the changes in CORE)
Includes other `minor` updates too.
=> OP-1075 remove old history tracking for packages a to d

src/main/java/org/isf/exa/model/Exam.java, src/main/java/org/isf/exa/model/ExamRow.java, src/main/java/org/isf/exa/service/ExamIoOperations.java, src/main/java/org/isf/exa/service/ExamRowIoOperations.java, src/main/java/org/isf/exatype/model/ExamType.java, src/main/java/org/isf/hospital/model/Hospital.java, src/main/java/org/isf/lab/manager/LabManager.java, src/main/java/org/isf/lab/model/Laboratory.java, src/main/java/org/isf/lab/service/LabIoOperations.java, src/main/java/org/isf/malnutrition/model/Malnutrition.java, src/main/java/org/isf/medicals/model/Medical.java, src/main/java/org/isf/medicalstock/model/Lot.java, src/main/java/org/isf/medicalstock/model/Movement.java, src/main/java/org/isf/medicalstockward/model/MedicalWard.java, src/main/java/org/isf/medicalstockward/model/MedicalWardId.java, src/main/java/org/isf/medicalstockward/model/MovementWard.java, src/main/java/org/isf/medstockmovtype/model/MovementType.java, src/main/java/org/isf/medtype/model/MedicalType.java, src/main/java/org/isf/menu/model/GroupMenu.java, src/main/java/org/isf/menu/model/User.java, src/main/java/org/isf/menu/model/UserGroup.java, src/main/java/org/isf/menu/model/UserMenuItem.java
See [OP-1075](https://openhospital.atlassian.net/browse/OP-1075)
Packages e to m
Includes other minor updates too.
[OP-1075]: https://openhospital.atlassian.net/browse/OP-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1075 remove old history tracking for packages e to m

src/main/java/org/isf/opd/model/Opd.java, src/main/java/org/isf/opd/service/OpdIoOperations.java, src/main/java/org/isf/operation/model/Operation.java, src/main/java/org/isf/operation/service/OperationIoOperations.java, src/main/java/org/isf/opetype/model/OperationType.java, src/main/java/org/isf/patient/model/Patient.java, src/main/java/org/isf/patient/service/PatientIoOperations.java, src/main/java/org/isf/patvac/manager/PatVacManager.java, src/main/java/org/isf/patvac/model/PatientVaccine.java, src/main/java/org/isf/patvac/service/PatVacIoOperations.java, src/main/java/org/isf/permissions/model/GroupPermission.java, src/main/java/org/isf/permissions/model/Permission.java, src/main/java/org/isf/pregtreattype/model/PregnantTreatmentType.java, src/main/java/org/isf/priceslist/model/Price.java, src/main/java/org/isf/priceslist/model/PriceList.java, src/main/java/org/isf/pricesothers/model/PricesOthers.java, src/main/java/org/isf/therapy/model/TherapyRow.java, src/main/java/org/isf/utils/time/RememberDates.java, src/main/java/org/isf/vaccine/manager/VaccineBrowserManager.java, src/main/java/org/isf/vaccine/model/Vaccine.java, src/main/java/org/isf/vaccine/service/VaccineIoOperations.java, src/main/java/org/isf/vactype/manager/VaccineTypeBrowserManager.java, src/main/java/org/isf/vactype/model/VaccineType.java, src/main/java/org/isf/vactype/service/VacTypeIoOperation.java, src/main/java/org/isf/visits/model/Visit.java, src/main/java/org/isf/ward/model/Ward.java
See [OP-1075](https://openhospital.atlassian.net/browse/OP-1075)
Packages o to w
Includes other minor updates too.
[OP-1075]: https://openhospital.atlassian.net/browse/OP-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OP-1075 remove old history tracking for packages o to w

src/main/java/org/isf/utils/db/AuditorAwareConfig.java, src/main/java/org/isf/utils/db/AuditorAwareInterface.java, src/main/java/org/isf/utils/db/JpaConfig.java
See OP-1165.
Tests performed with https://github.com/informatici/openhospital-api/pull/422.
=> OP-1165-fix-circular-reference-in-jpa-config

src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java
=> OP-1166 Fix lot validation

src/main/java/org/isf/disease/manager/DiseaseBrowserManager.java, src/main/java/org/isf/disease/service/DiseaseIoOperationRepository.java, src/main/java/org/isf/disease/service/DiseaseIoOperations.java, src/main/java/org/isf/opd/manager/OpdBrowserManager.java, src/test/java/org/isf/opd/test/Tests.java
=> OP-1137 additional validation upon OPD save/update

src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java, src/main/java/org/isf/medicalstock/service/LotIoOperationRepository.java, src/main/java/org/isf/medicalstock/service/MedicalStockIoOperations.java
See OP-1166.
The idea is to make everything more explicit for future reference in the code (and also avoid errors)
=> OP-1166 Fix lot validation when automaticlot in false and automaticlot out true

src/main/java/org/isf/medicalstock/service/MedicalStockIoOperations.java
See OP-1167.
Paired with https://github.com/informatici/openhospital-gui/pull/1935.
=> OP-1167 Add error for unexpected condition on lot management

src/main/java/org/isf/utils/file/FileTools.java, src/test/java/org/isf/utils/file/TestFileTools.java, src/test/resources/org/isf/utils/file/testFile.txt
=> OP-1141 Default passwords suggestion more simple html plain text

src/main/java/org/isf/medicalstock/manager/MovBrowserManager.java, src/main/java/org/isf/medicalstockward/manager/MovWardBrowserManager.java, src/main/java/org/isf/medicalstockward/model/MovementWard.java, src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java, src/main/java/org/isf/medicalstockward/service/MovementWardIoOperationRepository.java, src/test/java/org/isf/medicalstock/test/Tests.java, src/test/java/org/isf/medicalstockward/test/Tests.java
=> OP-1178 Change query to find the last movement in a ward.

src/main/java/org/isf/telemetry/daemon/TelemetryDaemon.java
See OP-312.
Fix NPE when TelemetryDaemon is not yet started.
=> OP-312 Fix for daemon not yet started

src/main/java/org/isf/utils/log/LogUtil.java
=> OP-1179 Change DailyRollingFileAppender to RollingFileAppender

pom.xml
See https://github.com/spring-projects/spring-framework/releases/tag/v5.3.32
=> Chore: update to SpringFramework 5.3.32

src/main/java/org/isf/medicalinventory/manager/MedicalInventoryManager.java, src/main/java/org/isf/medicalinventory/service/MedicalInventoryIoOperation.java
Here i have change OHException Type to OHServiceException
=> OP-1183 | 

src/main/java/org/isf/medicalinventory/manager/MedicalInventoryManager.java, src/main/java/org/isf/medicalinventory/service/MedicalInventoryIoOperation.java
=> OP-1199 Change OHException Type to OHServiceException

README.md
See OP-1205
Improve building section to run tests against MariaDB Docker instance
https://openhospital.atlassian.net/browse/OP-1205
=> OP-1205 Update README.md - Docker usage documentation in core

src/main/java/org/isf/accounting/manager/BillBrowserManager.java, src/main/java/org/isf/accounting/service/AccountingIoOperations.java, src/main/java/org/isf/admission/manager/AdmissionBrowserManager.java, src/main/java/org/isf/admission/service/AdmissionIoOperations.java, src/main/java/org/isf/admission/service/AdmissionPatientMergedEventListener.java, src/main/java/org/isf/admtype/manager/AdmissionTypeBrowserManager.java, src/main/java/org/isf/admtype/service/AdmissionTypeIoOperation.java, src/main/java/org/isf/agetype/manager/AgeTypeBrowserManager.java, src/main/java/org/isf/agetype/service/AgeTypeIoOperations.java, src/main/java/org/isf/anamnesis/manager/PatientHistoryManager.java, src/main/java/org/isf/anamnesis/service/PatientHistoryIoOperations.java, src/main/java/org/isf/dicom/manager/SqlDicomManager.java, src/main/java/org/isf/dicom/service/DicomIoOperations.java, src/main/java/org/isf/dicomtype/manager/DicomTypeBrowserManager.java, src/main/java/org/isf/dicomtype/service/DicomTypeIoOperation.java, src/main/java/org/isf/disctype/manager/DischargeTypeBrowserManager.java, src/main/java/org/isf/disctype/service/DischargeTypeIoOperation.java, src/main/java/org/isf/distype/manager/DiseaseTypeBrowserManager.java, src/main/java/org/isf/dlvrrestype/manager/DeliveryResultTypeBrowserManager.java, src/main/java/org/isf/dlvrrestype/service/DeliveryResultTypeIoOperation.java, src/main/java/org/isf/dlvrtype/manager/DeliveryTypeBrowserManager.java, src/main/java/org/isf/dlvrtype/service/DeliveryTypeIoOperation.java
See OP-1210
All unit tests pass.
=> OP-1210 Use Constructor injection for packages starting with A through D.

src/main/java/org/isf/exa/manager/ExamBrowsingManager.java, src/main/java/org/isf/exa/manager/ExamRowBrowsingManager.java, src/main/java/org/isf/exa/service/ExamIoOperations.java, src/main/java/org/isf/exa/service/ExamRowIoOperations.java, src/main/java/org/isf/examination/manager/ExaminationBrowserManager.java, src/main/java/org/isf/examination/service/ExaminationOperations.java, src/main/java/org/isf/examination/service/ExaminationPatientMergedEventListener.java, src/main/java/org/isf/exatype/manager/ExamTypeBrowserManager.java, src/main/java/org/isf/exatype/service/ExamTypeIoOperation.java, src/main/java/org/isf/hospital/manager/HospitalBrowsingManager.java, src/main/java/org/isf/hospital/service/HospitalIoOperations.java, src/main/java/org/isf/lab/manager/LabManager.java, src/main/java/org/isf/lab/manager/LabRowManager.java, src/main/java/org/isf/lab/service/LabIoOperations.java, src/main/java/org/isf/lab/service/LabPatientMergedEventListener.java
=> OP-1211 Use Constructor injection for packages starting with E to L.

src/main/java/org/isf/malnutrition/manager/MalnutritionManager.java, src/main/java/org/isf/malnutrition/service/MalnutritionIoOperation.java, src/main/java/org/isf/medicalinventory/manager/MedicalInventoryManager.java, src/main/java/org/isf/medicalinventory/manager/MedicalInventoryRowManager.java, src/main/java/org/isf/medicalinventory/service/MedicalInventoryIoOperation.java, src/main/java/org/isf/medicalinventory/service/MedicalInventoryRowIoOperation.java, src/main/java/org/isf/medicals/manager/MedicalBrowsingManager.java, src/main/java/org/isf/medicals/service/MedicalsIoOperations.java, src/main/java/org/isf/medicalstock/manager/MovBrowserManager.java, src/main/java/org/isf/medicalstock/manager/MovStockInsertingManager.java, src/main/java/org/isf/medicalstock/service/MedicalStockIoOperations.java, src/main/java/org/isf/medicalstockward/manager/MovWardBrowserManager.java, src/main/java/org/isf/medicalstockward/service/MedicalStockWardIoOperations.java, src/main/java/org/isf/medicalstockward/service/MovementWardPatientMergedEventListener.java, src/main/java/org/isf/medstockmovtype/manager/MedicalDsrStockMovementTypeBrowserManager.java, src/main/java/org/isf/medstockmovtype/service/MedicalDsrStockMovementTypeIoOperation.java, src/main/java/org/isf/medtype/manager/MedicalTypeBrowserManager.java, src/main/java/org/isf/medtype/service/MedicalTypeIoOperation.java, src/main/java/org/isf/menu/manager/Context.java, src/main/java/org/isf/menu/manager/UserBrowsingManager.java, src/main/java/org/isf/menu/manager/UserGroupManager.java, src/main/java/org/isf/menu/manager/UserSettingManager.java, src/main/java/org/isf/menu/service/MenuIoOperations.java
=> OP-1212 Use Constructor injection for Core packages starting with M

src/main/java/org/isf/opd/manager/OpdBrowserManager.java, src/main/java/org/isf/opd/service/OpdIoOperations.java, src/main/java/org/isf/opd/service/OpdPatientMergedEventListener.java, src/main/java/org/isf/operation/manager/OperationBrowserManager.java, src/main/java/org/isf/operation/manager/OperationRowBrowserManager.java, src/main/java/org/isf/operation/service/OperationIoOperations.java, src/main/java/org/isf/operation/service/OperationRowIoOperations.java, src/main/java/org/isf/opetype/manager/OperationTypeBrowserManager.java, src/main/java/org/isf/opetype/service/OperationTypeIoOperation.java, src/main/java/org/isf/patconsensus/manager/PatientConsensusBrowserManager.java, src/main/java/org/isf/patconsensus/service/PatientConsensusIoOperation.java, src/main/java/org/isf/patvac/manager/PatVacManager.java, src/main/java/org/isf/patvac/service/PatVacIoOperations.java, src/main/java/org/isf/patvac/service/VaccinePatientMergedEventListener.java, src/main/java/org/isf/permissions/manager/GroupPermissionManager.java, src/main/java/org/isf/permissions/manager/PermissionManager.java, src/main/java/org/isf/permissions/service/GroupPermissionIoOperations.java, src/main/java/org/isf/permissions/service/PermissionIoOperations.java, src/main/java/org/isf/pregtreattype/manager/PregnantTreatmentTypeBrowserManager.java, src/main/java/org/isf/pregtreattype/service/PregnantTreatmentTypeIoOperation.java, src/main/java/org/isf/priceslist/manager/PriceListManager.java, src/main/java/org/isf/priceslist/service/PricesListIoOperations.java, src/main/java/org/isf/pricesothers/manager/PricesOthersManager.java, src/main/java/org/isf/pricesothers/service/PriceOthersIoOperations.java
=> OP-1213 Use Constructor injection for Core packages starting with O and P

src/main/java/org/isf/serviceprinting/manager/PrintManager.java, src/main/java/org/isf/sessionaudit/manager/SessionAuditManager.java, src/main/java/org/isf/sessionaudit/service/SessionAuditIoOperation.java, src/main/java/org/isf/sms/manager/SmsManager.java, src/main/java/org/isf/sms/service/SmsOperations.java, src/main/java/org/isf/stat/manager/JasperReportsManager.java, src/main/java/org/isf/supplier/manager/SupplierBrowserManager.java, src/main/java/org/isf/supplier/service/SupplierOperations.java
=> OP-1215 Use Constructor injection for Core packages starting with S

src/main/java/org/isf/ward/model/Ward.java
=> OP-1219 Add Ward comparator to sort in combobox

pom.xml
=> Chore: update license plugin to 4.5 to match other repos
